---
title: "Publications"
---

<!-- Generated automatically from /Users/simurgh/Documents/Codex/spark-lab-site/data/samer-lahoud-ref-db.bib by scripts/generate_publications.py -->

<div class="pub-view-switch" role="tablist" aria-label="Publication sorting">
  <button class="pub-view-button is-active" type="button" data-view-target="year">By year</button>
  <button class="pub-view-button" type="button" data-view-target="category">By category</button>
</div>

<div class="pub-view" data-view-panel="category" hidden>


## Journal Articles


<a id="Durand%3A2024fr"></a>
[1] S. Durand, K. Khawam, D. Quadri, S. Lahoud, S. Martin, **Federated Learning Game in IoT Edge Computing**, *IEEE Access*, vol. 12, pp. 93060-93074, 2024. [doi](https://doi.org/10.1109/ACCESS.2024.3420814)


<a id="Fawaz%3A2023wu"></a>
[2] H. Fawaz, S. Lahoud, M.E. Helou, K. Khawam, **Queue-Aware Resource Allocation in Full-Duplex Multi-Cellular Wireless Networks**, *IEEE Journal on Selected Areas in Communications*, vol. 41, no. 9, pp. 2852-2863, 2023. [doi](https://doi.org/10.1109/JSAC.2023.3287541)


<a id="Loubany%3A2023cq"></a>
[3] A. Loubany, S. Lahoud, A.E. Samhat, M. El Helou, **Joint throughput-energy optimization in multi-gateway LoRaWAN networks**, *Telecommunication Systems*, vol. 84, no. 2, pp. 271–283, 2023. [doi](https://doi.org/10.1007/s11235-023-01048-8) [url](https://doi.org/10.1007/s11235-023-01048-8)


<a id="Loubany%3A2023rg"></a>
[4] A. Loubany, S. Lahoud, A.E. Samhat, M. El Helou, **Improving Energy Efficiency in LoRaWAN Networks with Multiple Gateways**, *Sensors*, vol. 23, no. 11, 2023. [doi](https://doi.org/10.3390/s23115315) [url](https://www.mdpi.com/1424-8220/23/11/5315)


<a id="Yassine%3A2023sr"></a>
[5] F. Yassine, M.E. Helou, S. Lahoud, O. Bazzi, **A Four-Sided Matching Game for Energy-Efficient Scheduling in Narrowband-IoT Networks**, *IEEE Access*, vol. 11, pp. 44482-44495, 2023. [doi](https://doi.org/10.1109/ACCESS.2023.3266443)


<a id="Taleb%3A2022zr"></a>
[6] H. Taleb, K. Khawam, S. Lahoud, M.E. Helou, S. Martin, **Pilot Contamination Mitigation in Massive MIMO Cloud Radio Access Networks**, *IEEE Access*, vol. 10, pp. 58212-58224, 2022. [doi](https://doi.org/10.1109/ACCESS.2022.3177629)


<a id="Yassine%3A2022sf"></a>
[7] F. Yassine, M. El Helou, S. Lahoud, O. Bazzi, **Energy-Efficient Uplink Scheduling in Narrowband IoT**, *Sensors*, vol. 22, no. 20, 2022. [doi](https://doi.org/10.3390/s22207744) [url](https://www.mdpi.com/1424-8220/22/20/7744)


<a id="Awada%3A2022hc"></a>
[8] Z. Awada, K. Boulos, M. El-Helou, K. Khawam, S. Lahoud, **Distributed multi-tenant RAN slicing in 5G networks**, *Wireless Networks*, 2022. [doi](https://doi.org/10.1007/s11276-022-03023-8) [url](https://doi.org/10.1007/s11276-022-03023-8)


<a id="Khawam%3A2022wd"></a>
[9] K. Khawam, H. Fawaz, S. Lahoud, O. Maillard, S. Martin, **A channel selection game for multi-operator LoRaWAN deployments**, *Computer Networks*, vol. 216, pp. 109185, 2022. [doi](https://doi.org/10.1016/j.comnet.2022.109185) [url](https://www.sciencedirect.com/science/article/pii/S1389128622002821)


<a id="Fawaz%3A2021pi"></a>
[10] H. Fawaz, K. Khawam, S. Lahoud, C. Adjih, S. Martin, **Joint Spreading Factor and Channel Assignment in Multi-Operator LoRaWAN Deployments**, *Sensors*, vol. 21, no. 1, 2021. [doi](https://doi.org/10.3390/s21010162) [pdf](http://samer.lahoud.fr/pub-pdf/sensors-21.pdf)


<a id="Fawaz%3A2021jt"></a>
[11] H. Fawaz, M. El Helou, S. Lahoud, K. Khawam, **A reinforcement learning approach to queue-aware scheduling in full-duplex wireless networks**, *Computer Networks*, vol. 189, pp. 107893, 2021. [doi](https://doi.org/10.1016/j.comnet.2021.107893) [pdf](http://samer.lahoud.fr/pub-pdf/comnet-21.pdf)


<a id="Fawaz%3A2020uo"></a>
[12] H. Fawaz, S. Lahoud, M. El Helou, **Queue-aware scheduling in full-duplex wireless networks**, *Wireless Networks*, 2020. [doi](https://doi.org/10.1007/s11276-020-02308-0) [pdf](http://samer.lahoud.fr/pub-pdf/wireless-20.pdf)


<a id="Lahad%3A2020qq"></a>
[13] B. Lahad, M. Ibrahim, S. Lahoud, K. Khawam, S. Martin, **Joint Modeling of TDD and Decoupled Uplink/Downlink Access in 5G HetNets with Multiple Small Cells Deployment**, *IEEE Transactions on Mobile Computing*, pp. 1-1, 2020. [doi](https://doi.org/10.1109/TMC.2020.2979447) [pdf](http://samer.lahoud.fr/pub-pdf/tmc-20a.pdf)


<a id="Khawam%3A2020ek"></a>
[14] K. Khawam, S. Lahoud, M. El Helou, S. Martin, G. Feng, **Coordinated Framework for Spectrum Allocation and User Association in 5G HetNets with mmWave**, *IEEE Transactions on Mobile Computing*, pp. 1-1, 2020. [doi](https://doi.org/10.1109/TMC.2020.3022681) [pdf](http://samer.lahoud.fr/pub-pdf/tmc-20b.pdf)


<a id="Fawaz%3A2020la"></a>
[15] H. Fawaz, K. Khawam, S. Lahoud, S. Martin, M. El Helou, **Cooperation for Spreading Factor Assignment in a Multi-Operator LoRaWAN Deployment**, *IEEE Internet of Things Journal*, pp. 1-1, 2020. [doi](https://doi.org/10.1109/JIOT.2020.3031681) [pdf](http://samer.lahoud.fr/pub-pdf/iotj-20.pdf)


<a id="Loubany%3A2020gd"></a>
[16] A. Loubany, S. Lahoud, R. El Chall, **Adaptive algorithm for spreading factor selection in LoRaWAN networks with multiple gateways**, *Computer Networks*, vol. 182, pp. 107491, 2020. [doi](https://doi.org/10.1016/j.comnet.2020.107491) [pdf](http://samer.lahoud.fr/pub-pdf/comnet-20b.pdf)


<a id="Taleb%3A2020it"></a>
[17] H. Taleb, K. Khawam, S. Lahoud, M.E. Helou, S. Martin, **A fully distributed approach for joint user association and RRH clustering in cloud radio access networks**, *Computer Networks*, vol. 182, pp. 107445, 2020. [doi](https://doi.org/10.1016/j.comnet.2020.107445) [pdf](http://samer.lahoud.fr/pub-pdf/comnet-20a.pdf)


<a id="el-chall%3A2019qy"></a>
[18] R. El Chall, S. Lahoud, M. El Helou, **LoRaWAN Network: Radio Propagation Models and Performance Evaluation in Various Environments in Lebanon**, *IEEE Internet of Things Journal*, pp. 1-1, 2019. [doi](https://doi.org/10.1109/JIOT.2019.2906838) [pdf](http://samer.lahoud.fr/pub-pdf/jiot-19.pdf)


<a id="Fawaz%3A2019wd"></a>
[19] H. Fawaz, K. Khawam, S. Lahoud, M. El Helou, **A Game Theoretic Framework for Power Allocation in Full-Duplex Wireless Networks**, *IEEE Access*, vol. 7, pp. 174013-174027, 2019. [doi](https://doi.org/10.1109/ACCESS.2019.2957316) [pdf](http://samer.lahoud.fr/pub-pdf/access-19.pdf)


<a id="farhat%3A2017fk"></a>
[20] S. Farhat, A.E. Samhat, S. Lahoud, B. Cousin, **Radio Access Network Sharing in 5G: Strategies and Benefits**, *Wireless Personal Communications*, 2017. [doi](https://doi.org/10.1007/s11277-017-4321-1) [pdf](http://samer.lahoud.fr/pub-pdf/wpc-17.pdf)


<a id="yassin%3A2017xr"></a>
[21] M. Yassin, S. Lahoud, M. Ibrahim, K. Khawam, D. Mezher, B. Cousin, **Cooperative resource management and power allocation for multiuser OFDMA networks**, *IET Communications*, vol. 11, no. 16, pp. 2552-2559, 2017. [doi](https://doi.org/10.1049/iet-com.2017.0201) [pdf](http://samer.lahoud.fr/pub-pdf/iet-17.pdf)


<a id="yassin%3A2017mz"></a>
[22] M. Yassin, S. Lahoud, K. Khawam, M. Ibrahim, D. Mezher, B. Cousin, **Centralized versus decentralized multi-cell resource and power allocation for multiuser OFDMA networks**, *Computer Communications*, vol. 107, pp. 112 - 124, 2017. [doi](https://doi.org/10.1016/j.comcom.2017.04.002) [pdf](http://samer.lahoud.fr/pub-pdf/comcom-17.pdf)


<a id="khawam%3A2016uq"></a>
[23] K. Khawam, S. Lahoud, M. Ibrahim, M. Yassin, S. Martin, M.E. Helou, F. Moety, **Radio access technology selection in heterogeneous networks**, *Physical Communication*, vol. 18, Part 2, pp. 125 - 139, 2016. [doi](https://doi.org/10.1016/j.phycom.2015.10.004) [pdf](http://samer.lahoud.fr/pub-pdf/phycom-15.pdf)


<a id="lahoud%3A2016kx"></a>
[24] S. Lahoud, K. Khawam, S. Martin, G. Feng, Z. Liang, J. Nasreddine, **Energy Efficient Joint Scheduling and Power Control in Multi-Cell Wireless Networks**, *IEEE Journal on Selected Areas in Communications*, vol. PP, no. 99, pp. 1-1, 2016. [doi](https://doi.org/10.1109/JSAC.2016.2611847) [pdf](http://samer.lahoud.fr/pub-pdf/jsac-16.pdf)


<a id="el-helou%3A2016qy"></a>
[25] M. El Helou, S. Lahoud, M. Ibrahim, K. Khawam, B. Cousin, D. Mezher, **A Hybrid Approach for Radio Access Technology Selection in Heterogeneous Wireless Networks**, *Wireless Personal Communications*, vol. 86, no. 2, pp. 789–834, 2016. [doi](https://doi.org/10.1007/s11277-015-2957-2) [pdf](https://hal.archives-ouvertes.fr/hal-01182891)


<a id="yassin%3A2015fi"></a>
[26] M. Yassin, M.A. AboulHassan, S. Lahoud, M. Ibrahim, D. Mezher, B. Cousin, E.A. Sourour, **Survey of ICIC Techniques in LTE Networks under Various Mobile Environment Parameters**, *Wireless Networks*, pp. 1, 2015. [url](https://hal.archives-ouvertes.fr/hal-01198389) [pdf](https://hal.archives-ouvertes.fr/hal-01198389/file/2015_09_12_HAL_Survey_of_ICIC_Techniques_in_LTE_Networks_under_Various_Mobile_Environment_Parameters.pdf)


<a id="moety%3A2015sj"></a>
[27] F. Moety, S. Lahoud, B. Cousin, K. Khawam, **Optimization models for the joint Power-Delay minimization problem in green wireless access networks**, *Computer Networks*, vol. 92, Part 1, pp. 148 - 167, 2015. [doi](https://doi.org/10.1016/j.comnet.2015.09.032) [pdf](http://samer.lahoud.fr/pub-pdf/comnet-15.pdf)


<a id="el-helou%3A2015cr"></a>
[28] M. El Helou, M. Ibrahim, S. Lahoud, K. Khawam, D. Mezher, B. Cousin, **A Network-Assisted Approach for RAT Selection in Heterogeneous Cellular Networks**, *IEEE Journal on Selected Areas in Communications - Special Issue on Recent Advances in Heterogenous Cellular Networks (JSAC - HCN)*, vol. 33, no. 6, pp. 1055-1067, June 2015. [doi](https://doi.org/10.1109/JSAC.2015.2416987) [pdf](http://samer.lahoud.fr/pub-pdf/jsac-15.pdf)


<a id="djarallah%3A2014fb"></a>
[29] N. Djarallah, H. Pouyllau, S. Lahoud, B. Cousin, **Multi-Constrained Path Computation for Inter-Domain QoS-capable Services**, *International Journal of Communication Networks and Distributed Systems*, vol. 12, pp. 1-22, 2014. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/ijcnds-12.pdf)


<a id="belghith%3A2014xz"></a>
[30] A. Belghith, B. Cousin, S. Lahoud, **Configurable Monitoring For Multi-Domain Networks**, *International Journal of Modern Engineering Research*, vol. 4, no. 2, pp. 65-89, February 2014. [pdf](http://samer.lahoud.fr/pub-pdf/ijmer-14.pdf)


<a id="frikha%3A2014kr"></a>
[31] A. Frikha, B. Cousin, S. Lahoud, **Applying p-cycle protection for a reliable IPTV service in IP-over-DWDM networks**, *Journal of Internet Services and Applications*, vol. 5, no. 1, 2014. [doi](https://doi.org/10.1186/1869-0238-5-3) [pdf](http://samer.lahoud.fr/pub-pdf/jisa-14.pdf)


<a id="frikha%3A2013lp"></a>
[32] A. Frikha, S. Lahoud, B. Cousin, **A Hybrid End-to-End QoS Path Computation Algorithm for PCE-Based Multi-Domain Networks**, *Journal of Network and Systems Management*, pp. 1-27, 2013. [doi](https://doi.org/10.1007/s10922-013-9273-5) [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/jnsm-13.pdf)


<a id="molnar%3A2012iw"></a>
[33] M. Molnar, A. Bellabas, S. Lahoud, **The cost optimal solution of the multi-constrained multicast routing problem**, *Computer Networks*, vol. 56, no. 13, pp. 3136 - 3149, 2012. [doi](https://doi.org/10.1016/j.comnet.2012.04.020)


<a id="bellabas%3A2012ez"></a>
[34] A. Bellabas, S. Lahoud, M. Molnar, **Performance Evaluation of Efficient Solutions for the QoS Unicast Routing**, *Journal of Networks*, vol. 7, no. 1, pp. 73-80, January 2012. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/jnet-11.pdf)


<a id="belghith%3A2012zh"></a>
[35] A. Belghith, S.B.H. Said, B. Cousin, S. Lahoud, **Export Methods in Fault Detection and Localization Mechanisms**, *IJCSI International Journal of Computer Science Issues*, vol. 9, no. 2, July 2012. [pdf](http://www.ijcsi.org/papers/IJCSI-9-4-2-463-471.pdf)


<a id="belghith%3A2012ta"></a>
[36] A. Belghith, S.B.H. Said, B. Cousin, S. Lahoud, **Collaboration Schemes Evaluation in Multi-domain Networks**, *IJCSI International Journal of Computer Science Issues*, vol. 9, no. 2, July 2012. [pdf](http://www.ijcsi.org/papers/IJCSI-9-4-2-472-480.pdf)


<a id="drid%3A2010vo"></a>
[37] H. Drid, S. Lahoud, B. Cousin, M. Molnar, **Survivability in multi-domain optical networks using p-cycles**, *Photonic Network Communications*, vol. 19, pp. 81-89, 2010. [doi](https://doi.org/10.1007/s11107-009-0213-y) [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/photonic-09.pdf)


<a id="drid%3A2010tp"></a>
[38] H. Drid, B. Cousin, M. Molnar, S. Lahoud, **A Survey of Survivability in Multi-domain Optical Networks**, *Computer Communications*, vol. 33, no. 8, pp. 1005 - 1012, 2010. [doi](https://doi.org/10.1016/j.comcom.2010.02.003) [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/comcom-10.pdf)


<a id="drid%3A2009tn"></a>
[39] H. Drid, B. Cousin, S. Lahoud, M. Molnar, **Protection par p-cycles dans les réseaux WDM**, *Technique et science informatiques*, vol. 28, no. 4, pp. 20, 2009. [doi](https://doi.org/10.3166/tsi.28.459-478) [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/tsi-09.pdf)





## Conference Papers


<a id="Khawam%3A2024lq"></a>
[1] K. Khawam, H. Taleb, S. Lahoud, H. Fawaz, D. Quadri, S. Martin, **Non-Cooperative Edge Server Selection Game for Federated Learning in IoT**, *NOMS 2024-2024 IEEE Network Operations and Management Symposium*, pp. 1-6, 2024. [doi](https://doi.org/10.1109/NOMS59830.2024.10575406)


<a id="Loubany%3A2023yi"></a>
[2] A. Loubany, S. Lahoud, A.E. Samhat, M.E. Helou, **Throughput Improvement for LoRaWAN Networks Considering IoT Applications Priority**, *2023 6th Conference on Cloud and Internet of Things (CIoT)*, pp. 206-210, 2023. [doi](https://doi.org/10.1109/CIoT57267.2023.10084887)


<a id="Rayess%3A2023bf"></a>
[3] J.E. Rayess, K. Khawam, S. Lahoud, M.E. Helou, S. Martin, **Study of LoRaWAN Networks Reliability**, *2023 6th Conference on Cloud and Internet of Things (CIoT)*, pp. 200-205, 2023. [doi](https://doi.org/10.1109/CIoT57267.2023.10084880)


<a id="Rayess%3A2023km"></a>
[4] J.E. Rayess, K. Khawam, S. Lahoud, M.E. Helou, S. Martin, **RALI: Increasing Reliability in LoRaWAN through Repetition and Iteration**, *2023 IEEE Wireless Communications and Networking Conference (WCNC)*, pp. 1-6, 2023. [doi](https://doi.org/10.1109/WCNC55385.2023.10118962)


<a id="Loubany%3A2023bq"></a>
[5] A. Loubany, A.E. Samhat, S. Lahoud, M. El Helou, **Energy Efficiency Enhancement for LoRaWAN Networks with Multiple Gateways**, *2023 IEEE International Conference on Communications (ICC): IoT and Sensor Networks Symposium (IEEE ICC'23 - IoTSN Symposium)*, Rome, Italy, May 2023.


<a id="Khawam%3A2023ng"></a>
[6] K. Khawam, S. Lahoud, C. Adjih, S. Makhoul, R. Al Tawil, S. Martin, **Edge Learning as a Hedonic Game in LoRaWAN**, *2023 IEEE International Conference on Communications (ICC): IoT and Sensor Networks Symposium (IEEE ICC'23 - IoTSN Symposium)*, Rome, Italy, May 2023.


<a id="Awada%3A2023le"></a>
[7] Z. Awada, M. El Helou, K. Khawam, S. Lahoud, **Dynamic Multi-Tenant RAN Slicing for eMBB, URLLC, and mMTC in 5G Networks**, *2023 26th International Symposium on Wireless Personal Multimedia Communications (WPMC)*, pp. 1-7, 2023. [doi](https://doi.org/10.1109/WPMC59531.2023.10338951)


<a id="Awada%3A2023dw"></a>
[8] Z. Awada, K. Khawam, S. Lahoud, M. El Helou, **A Stackelberg Game for Multi-Tenant RAN Slicing in 5G Networks**, *2023 IEEE Symposium on Computers and Communications (ISCC)*, pp. 1058-1061, 2023. [doi](https://doi.org/10.1109/ISCC58397.2023.10218208)


<a id="Iskandarani%3A2023jy"></a>
[9] H. Iskandarani, H.Y. Kanaan, M. Helou, K. Khawam, S. Lahoud, K. Al-Haddad, **A Neural-Network-Based Controller for a Three- Phase Dual-Active-Bridge DC-DC Converter**, *2023 IEEE Conference on Power Electronics and Renewable Energy (CPERE)*, pp. 1-7, 2023. [doi](https://doi.org/10.1109/CPERE56564.2023.10119632)


<a id="Awada%3A2023vf"></a>
[10] Z. Awada, M. El Helou, K. Khawam, S. Lahoud, **A Multi-Armed Bandit Game for Multi-Tenant RAN Slicing**, *2023 IEEE 4th International Multidisciplinary Conference on Engineering Technology (IMCET)*, pp. 62-68, 2023. [doi](https://doi.org/10.1109/IMCET59736.2023.10368268)


<a id="Loubany%3A2022if"></a>
[11] A. Loubany, A.E. Samhat, S. Lahoud, M.E. Helou, **Battery-Less LoRaWAN Network using Energy Harvesting: Improving Network Throughput**, *2022 IEEE 33rd Annual International Symposium on Personal, Indoor and Mobile Radio Communications (PIMRC)*, pp. 1032-1037, 2022. [doi](https://doi.org/10.1109/PIMRC54779.2022.9977716)


<a id="Yassine%3A2021bh"></a>
[12] F. Yassine, M. El Helou, S. Lahoud, O. Bazzi, **Performance of Narrowband IoT Link Adaptation with Rate and Energy Objectives**, *2021 IEEE 3rd International Multidisciplinary Conference on Engineering Technology (IMCET)*, pp. 6-10, 2021. [doi](https://doi.org/10.1109/IMCET53404.2021.9665562)


<a id="Yassine%3A2021pd"></a>
[13] F. Yassine, M.E. Helou, O. Bazzi, S. Lahoud, **Investigation on Narrowband IoT Link Adaptation with Rate and Energy Objectives**, *2021 International Wireless Communications and Mobile Computing (IWCMC)*, pp. 412-417, 2021. [doi](https://doi.org/10.1109/IWCMC51323.2021.9498738)


<a id="Ayoub%3A2021mz"></a>
[14] I. Ayoub, I. Hmedoush, C. Adjih, K. Khawam, S. Lahoud, **Deep-IRSA: A Deep Reinforcement Learning Approach to Irregular Repetition Slotted ALOHA**, *2021 10th IFIP International Conference on Performance Evaluation and Modeling in Wireless and Wired Networks (PEMWN)*, pp. 1-6, 2021. [doi](https://doi.org/10.23919/PEMWN53042.2021.9664720)


<a id="Lahad%3A2020ph"></a>
[15] B. Lahad, M. Ibrahim, S. Lahoud, K. Khawam, S. Martin, **Uplink/Downlink Decoupled Access with Dynamic TDD in 5G HetNets**, *2020 International Wireless Communications and Mobile Computing (IWCMC)*, pp. 1330-1335, 2020. [doi](https://doi.org/10.1109/IWCMC48107.2020.9148375) [pdf](http://samer.lahoud.fr/pub-pdf/iwcmc-20.pdf)


<a id="Martinez%3A2020cs"></a>
[16] I. Martinez, F. Nouvel, S. Lahoud, P. Tanguy, M.E. Helou, **On the Performance Evaluation of LoRaWAN with Re-transmissions under Jamming**, *2020 IEEE Symposium on Computers and Communications (ISCC)*, pp. 1-7, 2020. [doi](https://doi.org/10.1109/ISCC50000.2020.9219644) [pdf](http://samer.lahoud.fr/pub-pdf/iscc-20.pdf)


<a id="Ta%3A2019eu"></a>
[17] D. Ta, K. Khawam, S. Lahoud, C. Adjih, S. Martin, **LoRa-MAB: Toward an Intelligent Resources Allocation Approach for LoRaWAN Networks**, *2019 IEEE Global Communications Conference: Selected Areas in Communications: Internet of Things (Globecom2019 SAC IoT)*, Waikoloa, USA, December 2019. [pdf](http://samer.lahoud.fr/pub-pdf/globecom-19.pdf)


<a id="Ta%3A2019yg"></a>
[18] D. Ta, K. Khawam, S. Lahoud, C. Adjih, S. Martin, **LoRa-MAB: A Flexible Simulator for Decentralized Learning Resource Allocation in IoT Networks**, *2019 12th IFIP Wireless and Mobile Networking Conference (WMNC)*, pp. 55-62, Sep. 2019. [doi](https://doi.org/10.23919/WMNC.2019.8881393) [pdf](http://samer.lahoud.fr/pub-pdf/wmnc-19.pdf)


<a id="ben-dhia%3A2019uq"></a>
[19] I. Ben Dhia, M. Bouhtou, T. En-Najjary, S. Lahoud, X. Lagrange, **Dynamic Access Point Selection and Resource Allocation in Multi-Technology Wireless Network**, *2019 IEEE Wireless Communications and Networking Conference (WCNC) (IEEE WCNC 2019)*, Marrakech, Morocco, April 2019. [pdf](http://samer.lahoud.fr/pub-pdf/wcnc-19.pdf)


<a id="Fawaz%3A2019fv"></a>
[20] H. Fawaz, K. Khawam, S. Lahoud, M. El Helou, **A Game Theoretic Approach for Power Allocation in Full Duplex Wireless Networks**, *2019 IEEE 30th Annual International Symposium on Personal, Indoor and Mobile Radio Communications (PIMRC): Track 3: Mobile and Wireless Networks (IEEE PIMRC 2019 - Track 3)*, Istanbul, Turkey, September 2019. [pdf](http://samer.lahoud.fr/pub-pdf/pimrc-19.pdf)


<a id="fawaz%3A2018rt"></a>
[21] H. Fawaz, S. Lahoud, M. El Helou, M. Ibrahim, **Queue-Aware Scheduling in Full Duplex OFDMA Wireless Networks with Imperfect Channel State Information**, *European Wireless 2018 (EW 2018)*, Catania, Italy, May 2018. [pdf](http://samer.lahoud.fr/pub-pdf/ew-18.pdf)


<a id="fawaz%3A2018ly"></a>
[22] H. Fawaz, S. Lahoud, M. El Helou, J. Saad, **Queue-Aware Priority Based Scheduling and Power Allocation in Full-Duplex OFDMA Cellular Networks**, *2018 25th International Conference on Telecommunications (ICT) (ICT 2018)*, Saint Malo, France, June 2018. [pdf](http://samer.lahoud.fr/pub-pdf/ict-a-18.pdf)


<a id="fawaz%3A2018vn"></a>
[23] H. Fawaz, S. Lahoud, M. El Helou, M. Ibrahim, **Optimal Max-SINR Scheduling in Full-Duplex OFDMA Cellular Networks with Dynamic Arrivals**, *2018 Wireless Days (WD) (WD'18)*, Dubai, United Arab Emirates, April 2018. [pdf](http://samer.lahoud.fr/pub-pdf/wd-18.pdf)


<a id="taleb%3A2018qf"></a>
[24] H. Taleb, S. Lahoud, K. Khawam, M. El Helou, S. Martin, **Multi-objective Optimization for RRH clustering in Cloud Radio Access Networks**, *2018 International Conference on Computer and Applications (ICCA) (ICCA-18)*, Beirut, Lebanon, July 2018. [pdf](http://samer.lahoud.fr/pub-pdf/icca-b-18.pdf)


<a id="taleb%3A2018ul"></a>
[25] H. Taleb, M. El Helou, K. Khawam, S. Lahoud, S. Martin, **Joint User Association and RRH Clustering in Cloud Radio Access Networks**, *2018 Tenth International Conference on Ubiquitous and Future Networks (ICUFN) (ICUFN 2018)*, Prague, Czech Republic, July 2018. [pdf](http://samer.lahoud.fr/pub-pdf/icufn-18.pdf)


<a id="lahad%3A2018pd"></a>
[26] B. Lahad, M. Ibrahim, S. Lahoud, K. Khawam, S. Martin, **Analytical Evaluation of Decoupled Uplink and Downlink Access in TDD 5G HetNets**, *2018 IEEE 29th Annual International Symposium on Personal, Indoor and Mobile Radio Communications (PIMRC) (IEEE PIMRC 2018)*, Bologna, Italy, September 2018. [pdf](http://samer.lahoud.fr/pub-pdf/pimrc-18.pdf)


<a id="taleb%3A2018gf"></a>
[27] H. Taleb, M. El Helou, S. Lahoud, K. Khawam, S. Martin, **An Efficient Heuristic for Joint User Association and RRH Clustering in Cloud Radio Access Networks**, *2018 25th International Conference on Telecommunications (ICT) (ICT 2018)*, Saint Malo, France, June 2018. [pdf](http://samer.lahoud.fr/pub-pdf/ict-b-18.pdf)


<a id="lahad%3A2018ys"></a>
[28] B. Lahad, M. Ibrahim, K. Khawam, S. Martin, S. Lahoud, **A Statistical Model for Uplink/Downlink Intercell Interference and Cell Capacity in TDD HetNets**, *IEEE ICC 2018 Wireless Communications Symposium (ICC'18 WCS)*, Kansas City, USA, May 2018. [pdf](http://samer.lahoud.fr/pub-pdf/icc-18.pdf)


<a id="fawaz%3A2018ve"></a>
[29] H. Fawaz, S. Lahoud, M. El Helou, **A Queue-Aware Discrete Scheduling Simulator for Full-Duplex OFDMA Wireless Networks**, *2018 International Conference on Computer and Applications (ICCA) (ICCA-18)*, Beirut, Lebanon, July 2018. [pdf](http://samer.lahoud.fr/pub-pdf/icca-a-18.pdf)


<a id="said%3A2017ij"></a>
[30] S.B.H. Said, B. Cousin, S. Lahoud, **Software defined networking (SDN) for reliable user connectivity in 5G networks**, *2017 IEEE Conference on Network Softwarization (NetSoft)*, pp. 1-5, July 2017. [doi](https://doi.org/10.1109/NETSOFT.2017.8004219) [pdf](http://samer.lahoud.fr/pub-pdf/netsoft-17.pdf)


<a id="dhia%3A2017sp"></a>
[31] I.B. Dhia, M. Bouhtou, T. En-Najjary, S. Lahoud, X. Lagrange, **Optimization of access points selection and resource allocation in heterogeneous wireless network**, *2017 IEEE 28th Annual International Symposium on Personal, Indoor, and Mobile Radio Communications (PIMRC)*, pp. 1-7, Oct 2017. [doi](https://doi.org/10.1109/PIMRC.2017.8292261) [pdf](http://samer.lahoud.fr/pub-pdf/pimrc-17.pdf)


<a id="fawaz%3A2017ve"></a>
[32] H. Fawaz, S. Lahoud, M. El Helou, M. Ibrahim, **On Scheduling in Full-Duplex OFDMA Cellular Networks**, *23th LAAS International Science Conference (LAAS'17)*, Kaslik, Lebanon, pp. 52-53, April 2017. [pdf](http://samer.lahoud.fr/pub-pdf/laas-17.pdf)


<a id="fawaz%3A2017ul"></a>
[33] H. Fawaz, S. Lahoud, M. Ibrahim, M. El Helou, **Max-SINR Scheduling in Full-Duplex OFDMA Cellular Networks with Dynamic Arrivals**, *2017 IEEE Symposium on Computers and Communications (ISCC) (ISCC 2017)*, Heraklion, Greece, pp. 493-498, July 2017. [pdf](http://samer.lahoud.fr/pub-pdf/iscc-17b.pdf)


<a id="maaz%3A2017ly"></a>
[34] B. Maaz, K. Khawam, S. Lahoud, J. Nasreddine, S. Tohme, **Joint User Association, Power Control and Scheduling in Multi-Cell 5G Networks**, *2017 IEEE Wireless Communications and Networking Conference (WCNC) (IEEE WCNC 2017)*, San Francisco, USA, March 2017. [pdf](http://samer.lahoud.fr/pub-pdf/wcnc-17.pdf)


<a id="rabah%3A2017gf"></a>
[35] G. Rabah, O.D. Dugeon, S. Lahoud, G. Texier, **Demonstration of Segment Routing with SDN Based Label Stack Optimization**, *2017 20th Conference on Innovations in Clouds, Internet and Networks (ICIN) (ICIN 2017)*, Paris, France, pp. 143-145, March 2017. [pdf](http://samer.lahoud.fr/pub-pdf/icin-17.pdf)


<a id="taleb%3A2017qf"></a>
[36] H. Taleb, K. Khawam, S. Lahoud, M. El Helou, S. Martin, **Centralized and Distributed RRH Clustering in Cloud Radio Access Networks**, *2017 IEEE Symposium on Computers and Communications (ISCC) (ISCC 2017)*, Heraklion, Greece, pp. 1094-1100, July 2017. [pdf](http://samer.lahoud.fr/pub-pdf/iscc-17a.pdf)


<a id="maaz%3A2017rt"></a>
[37] B. Maaz, K. Khawam, J. Nasreddine, S. Lahoud, S. Tohme, **Achieving Power and Energy Efficiency in Self-Organizing Networks**, *2017 14th IEEE Annual Consumer Communications & Networking Conference (CCNC) (CCNC 2017)*, Las Vegas, USA, January 2017. [pdf](http://samer.lahoud.fr/pub-pdf/ccnc-17.pdf)


<a id="guedrez%3A2017hc"></a>
[38] R. Guedrez, O. Dugeon, S. Lahoud, G. Texier, **A new method for encoding MPLS segment routing TE paths**, *2017 8th International Conference on the Network of the Future (NOF)*, pp. 58-65, Nov 2017. [doi](https://doi.org/10.1109/NOF.2017.8251221) [pdf](http://samer.lahoud.fr/pub-pdf/nof-17.pdf)


<a id="guedrez%3A2016yq"></a>
[39] R. Guedrez, O. Dugeon, S. Lahoud, G. Texier, **Label encoding algorithm for MPLS Segment Routing**, *2016 IEEE 15th International Symposium on Network Computing and Applications (NCA)*, pp. 113-117, Oct 2016. [doi](https://doi.org/10.1109/NCA.2016.7778603) [pdf](http://samer.lahoud.fr/pub-pdf/nca-16.pdf)


<a id="maaz%3A2016vn"></a>
[40] B. Maaz, K. Khawam, Y. Hayel, S. Lahoud, S. Martin, D. Quadri, **Joint user association, scheduling and power control in multi-cell networks**, *2016 IEEE 12th International Conference on Wireless and Mobile Computing, Networking and Communications (WiMob)*, pp. 1-7, Oct 2016. [doi](https://doi.org/10.1109/WiMOB.2016.7763205) [pdf](http://samer.lahoud.fr/pub-pdf/wimob-16.pdf)


<a id="yassin%3A2016uq"></a>
[41] M. Yassin, S. Lahoud, M. Ibrahim, K. Khawam, D. Mezher, B. Cousin, **Centralized multi-cell resource and power allocation for multiuser OFDMA networks**, *2016 IFIP Networking Conference (IFIP Networking) and Workshops*, pp. 162-170, May 2016. [doi](https://doi.org/10.1109/IFIPNetworking.2016.7497211) [pdf](http://samer.lahoud.fr/pub-pdf/networking-16.pdf)


<a id="boulos%3A2015zv"></a>
[42] K. Boulos, M. El Helou, S. Lahoud, **RRH clustering in cloud radio access networks**, *Applied Research in Computer Science and Engineering (ICAR), 2015 International Conference on*, pp. 1-6, Oct 2015. [doi](https://doi.org/10.1109/ARCSE.2015.7338135) [pdf](http://samer.lahoud.fr/pub-pdf/icar-15a.pdf)


<a id="farhat%3A2015sw"></a>
[43] S. Farhat, A.E. Samhat, S. Lahoud, B. Cousin, **Pricing Strategies in Multi-Operator Heterogeneous Wireless Networks**, *NTMS'2015 - Mobility & Wireless Networks Track (NTMS'2015 Mobility & Wireless Networks Track)*, Paris, France, July 2015. [pdf](http://samer.lahoud.fr/pub-pdf/ntms-15a.pdf)


<a id="yassin%3A2015xd"></a>
[44] M. Yassin, S. Lahoud, M. Ibrahim, K. Khawam, D. Mezher, B. Cousin, **Non-Cooperative Inter-Cell Interference Coordination Technique for Increasing Throughput Fairness in LTE Networks**, *VTC Spring 2015*, 2015. [pdf](http://samer.lahoud.fr/pub-pdf/vtc-15.pdf)


<a id="maaz%3A2015qy"></a>
[45] B. Maaz, K. Khawam, S. Tohme, S. Martin, S. Lahoud, J. Nasreddine, **Joint scheduling and power control in multi-cell networks for inter-cell interference coordination**, *Wireless and Mobile Computing, Networking and Communications (WiMob), 2015 IEEE 11th International Conference on*, pp. 778-785, Oct 2015. [doi](https://doi.org/10.1109/WiMOB.2015.7348041) [pdf](http://samer.lahoud.fr/pub-pdf/wimob-15.pdf)


<a id="maaz%3A2015px"></a>
[46] B. Maaz, K. Khawam, S. Tohme, S. Lahoud, J. Nasreddine, **Inter-cell interference coordination based on power control for self-organized 4G systems**, *Digital Information and Communication Technology and its Applications (DICTAP), 2015 Fifth International Conference on*, pp. 149-154, April 2015. [doi](https://doi.org/10.1109/DICTAP.2015.7113188) [pdf](http://samer.lahoud.fr/pub-pdf/dictap-15b.pdf)


<a id="farhat%3A2015hs"></a>
[47] S. Farhat, A. Samhat, S. Lahoud, B. Cousin, **Comparison between access selection algorithms in multi-operator wireless networks**, *Applied Research in Computer Science and Engineering (ICAR), 2015 International Conference on*, pp. 1-8, Oct 2015. [doi](https://doi.org/10.1109/ARCSE.2015.7338132) [pdf](http://samer.lahoud.fr/pub-pdf/icar-15b.pdf)


<a id="aboulhassan%3A2015et"></a>
[48] M.A. AboulHassan, M. Yassin, S. Lahoud, M. Ibrahim, D. Mezher, B. Cousin, E. Sourour, **Classification and Comparative Analysis of Inter-Cell Interference Coordination Techniques in LTE Networks**, *NTMS'2015 - Mobility & Wireless Networks Track (NTMS'2015 Mobility & Wireless Networks Track)*, Paris, France, July 2015. [pdf](http://samer.lahoud.fr/pub-pdf/ntms-15b.pdf)


<a id="farhat%3A2015fh"></a>
[49] S. Farhat, Z. Chahine, A. Samhat, S. Lahoud, B. Cousin, **Access selection and joint pricing in multi-operator wireless networks: A Stackelberg game**, *Digital Information and Communication Technology and its Applications (DICTAP), 2015 Fifth International Conference on*, pp. 38-43, April 2015. [doi](https://doi.org/10.1109/DICTAP.2015.7113167) [pdf](http://samer.lahoud.fr/pub-pdf/dictap-15a.pdf)


<a id="yassin%3A2015lo"></a>
[50] M. Yassin, Y. Dirani, M. Ibrahim, S. Lahoud, D. Mezher, B. Cousin, **A Novel Dynamic Inter-Cell Interference Coordination Technique for LTE Networks**, *2015 IEEE 26th International Symposium on Personal, Indoor and Mobile Radio Communications - (PIMRC): Mobile and Wireless Networks (IEEE PIMRC2015 Mobile & Wireless)*, Hong Kong, P.R. China, pp. 1742-1747, August 2015. [pdf](http://samer.lahoud.fr/pub-pdf/pimrc-15.pdf)


<a id="moety%3A2015pr"></a>
[51] F. Moety, S. Lahoud, B. Cousin, K. Khawam, **A Heuristic Algorithm for Joint Power-Delay Minimization in Green Wireless Access Networks**, *2015 International Conference on Computing, Networking and Communications (ICNC), Workshop on Computing, Networking and Communications (CNC) (ICNC'15 CNC Workshop)*, Anaheim, USA, February 2015. [pdf](http://samer.lahoud.fr/pub-pdf/cnc-14.pdf)


<a id="el-helou%3A2014bx"></a>
[52] M. El Helou, M. Ibrahim, S. Lahoud, K. Khawam, **Optimizing Network Information for Radio Access Technology Selection**, *19th IEEE Symposium on Computers and Communications (IEEE ISCC 2014)*, Madeira, Portugal, June 2014. [pdf](http://samer.lahoud.fr/pub-pdf/iscc-14.pdf)


<a id="moety%3A2014le"></a>
[53] F. Moety, S. Lahoud, B. Cousin, K. Khawam, **Joint Power-Delay Minimization in 4G Wireless Networks**, *2014 Wireless Days conference (WD'14)*, Rio de Janeiro, Brazil, November 2014. [pdf](http://samer.lahoud.fr/pub-pdf/wd-14.pdf)


<a id="farhat%3A2014ya"></a>
[54] S. Farhat, A.E. Samhat, S. Lahoud, **Hybrid Decision Algorithm for Access Selection in Multi-Operator Networks**, *IEEE WCNC'14 Track 3 (Mobile and Wireless Networks) (IEEE WCNC'14 Track 3 : NET)*, Istanbul, Turkey, April 2014. [pdf](http://samer.lahoud.fr/pub-pdf/wcnc-14.pdf)


<a id="khawam%3A2014wb"></a>
[55] K. Khawam, A. Adouane, S. Lahoud, S. Tohme, J. Cohen, **Game Theoretic Framework for Power Control in InterCell Interference Coordination**, *IFIP Networking 2014 Conference (Networking 2014)*, Trondheim, Norway, June 2014. [pdf](http://samer.lahoud.fr/pub-pdf/networking-14.pdf)


<a id="farhat%3A2014oa"></a>
[56] S. Farhat, A. Samhat, S. Lahoud, B. Cousin, **Best operator policy in a heterogeneous wireless network**, *e-Technologies and Networks for Development (ICeND), 2014 Third International Conference on*, pp. 53-57, April 2014. [doi](https://doi.org/10.1109/ICeND.2014.6991192) [pdf](http://samer.lahoud.fr/pub-pdf/icend-14.pdf)


<a id="yassin%3A2014ct"></a>
[57] M. Yassin, S. Lahoud, M. Ibrahim, K. Khawam, **A Downlink Power Control Heuristic Algorithm for LTE Networks**, *21st International Conference on Telecommunications (ICT 2014)*, Lisbon, Portugal, May 2014. [pdf](http://samer.lahoud.fr/pub-pdf/ict-14.pdf)


<a id="el-helou%3A2013sh"></a>
[58] M. El Helou, S. Lahoud, M. Ibrahim, K. Khawam, **Satisfaction-based Radio Access Technology Selection in Heterogeneous Wireless Networks**, *Wireless Days (WD), 2013 IFIP*, pp. 1-4, 2013. [doi](https://doi.org/10.1109/WD.2013.6686461) [pdf](http://samer.lahoud.fr/pub-pdf/wd-13.pdf)


<a id="el-helou%3A2013xi"></a>
[59] M. El Helou, M. Ibrahim, S. Lahoud, K. Khawam, **Radio Access Selection Approaches in Heterogeneous Wireless Networks**, *2013 IEEE 9th International Conference on Wireless and Mobile Computing, Networking and Communications (WiMob) (WiMob'2013)*, Lyon, France, October 2013. [pdf](http://samer.lahoud.fr/pub-pdf/wimob-13.pdf)


<a id="moety%3A2013jh"></a>
[60] F. Moety, S. Lahoud, B. Cousin, K. Khawam, **Power-Delay Tradeoffs in Green Wireless Access Networks**, *VTC Fall 2013*, Las Vegas, USA, 2013. [pdf](http://samer.lahoud.fr/pub-pdf/vtc-13.pdf)


<a id="moety%3A2013ri"></a>
[61] F. Moety, S. Lahoud, K. Khawam, B. Cousin, **Joint Power-Delay Minimization in Green Wireless Access Networks**, *2013 IEEE 24th International Symposium on Personal, Indoor and Mobile Radio Communications: Mobile and Wireless Networks (PIMRC'13 - Mobile and Wireless Networks)*, London, United Kingdom, September 2013. [pdf](http://samer.lahoud.fr/pub-pdf/pimrc-13a.pdf)


<a id="khawam%3A2013wm"></a>
[62] K. Khawam, J. Cohen, S. Lahoud, P. Muhlethaler, S. Tohme, **AP association in a IEEE 802.11 WLAN**, *Personal Indoor and Mobile Radio Communications (PIMRC), 2013 IEEE 24th International Symposium on*, pp. 2142-2147, Sept 2013. [pdf](http://samer.lahoud.fr/pub-pdf/pimrc-13b.pdf)


<a id="el-helou%3A2013pz"></a>
[63] M. El Helou, S. Lahoud, M. Ibrahim, K. Khawam, **A Hybrid Approach for Radio Access Technology Selection in Heterogeneous Wireless Networks**, *European Wireless 2013 (EW2013)*, Guildford, United Kingdom, April 2013. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/ew-13.pdf)


<a id="yassin%3A2013mq"></a>
[64] M. Yassin, S. Lahoud, M. Ibrahim, **A Hybrid Approach for RAT Selection in Wireless Heterogeneous Networks**, *The 3rd International Conference on Communications and Information Technology (ICCIT-2013): Wireless Communications and Signal Processing (ICCIT-2013 WCSP)*, Beirut, Lebanon, June 2013. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/iccit-13.pdf)


<a id="frikha%3A2012xh"></a>
[65] A. Frikha, S. Lahoud, B. Cousin, M. Molnar, **Reliable Multicast Sessions Provisioning in Sparse Light-Splitting DWDM Networks using P-Cycles**, *2012 Annual IEEE Communications Quality and Reliability International Workshop (CQR2012)*, San Diego CA, USA, May 2012. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/cqr-12.pdf)


<a id="belghith%3A2012oy"></a>
[66] A. Belghith, S.B. Said, B. Cousin, S. Lahoud, **QoS Fault Detection and Localization Mechanisms (FDLM) in Multi-domain Networks Adapted to Export Methods**, *4th International Conference on Advanced Communication Technology 2012 (ICACT 2012)*, PyeongChang, Korea, 2012. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/icact-12.pdf)


<a id="belghith%3A2012pt"></a>
[67] A. Belghith, S.B. Said, B. Cousin, S. Lahoud, **Proactive and Reactive Collaboration Schemes for Multi-domain Networks Monitoring**, *Engineering-IT applications 2012 (EITA 2012)*, Hong Kong, P.R. China, 2012. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/comcomap-12.pdf)


<a id="salhi%3A2012bu"></a>
[68] E. Salhi, S. Lahoud, B. Cousin, **Localization of Single Link-Level Network Anomalies**, *21st International Conference on Computer Communications and Networks (ICCCN 2012)*, Munich, Germany, July 2012. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/icccn-12.pdf)


<a id="moety%3A2012wa"></a>
[69] F. Moety, M. Ibrahim, S. Lahoud, K. Khawam, **Distributed Heuristic Algorithms for RAT Selection in Wireless Heterogeneous Networks**, *2012 IEEE Wireless Communications and Networking Conference: Mobile and Wireless Networks (IEEE WCNC 2012 Track 3 Mobile & Wireless)*, Paris, France, April 2012. [pdf](http://dl.dropbox.com/u/45967765/Publications/wcnc-12.pdf)


<a id="frikha%3A2012dl"></a>
[70] A. Frikha, S. Lahoud, B. Cousin, **Candidate-Cycle-based Heuristic Algorithm for Node-and-Link Protection of Dynamic Multicast Traffic in Optical DWDM Networks**, *The International Conference on Information Networking (ICOIN 2012)*, Bali, Indonesia, February 2012. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/icoin-12.pdf)


<a id="jawhar%3A2011nq"></a>
[71] S. Jawhar, B. Cousin, S. Lahoud, **Required Density of Multicast Capable Optical Cross-Connects to Assure Efficient Multicasting**, *First International Conference on Networking and Future Internet (ICNFI 2011)*, Paris, France, 2011. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/icnfi-11.pdf)


<a id="belghith%3A2011ix"></a>
[72] A. Belghith, B. Cousin, S. Lahoud, S.B. Said, **Proposal for the Configuration of multi-domain Network Monitoring Architecture**, *The International Conference on Information Networking (ICOIN 2011)*, Kuala Lumpur, Malaysia, pp. 7 - 12, January 2011. [doi](https://doi.org/10.1109/ICOIN.2011.5723105) [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/icoin-11.pdf)


<a id="jawhar%3A2011gd"></a>
[73] S. Jawhar, B. Cousin, S. Lahoud, **Placement of Light Splitters in Optical Networks**, *Deuxième colloque sur les réseaux large bande et Internet rapide*, Beirut, Lebanon, March 2011. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/relabira-11.pdf)


<a id="frikha%3A2011qz"></a>
[74] A. Frikha, S. Lahoud, **Performance Evaluation of Pre-computation Algorithms for Inter-Domain QoS Routing**, *The 18th International Conference on Telecommunications, ICT 2011*, Ayia Napa, Cyprus, 5 2011. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/ict-11.pdf)


<a id="khawam%3A2011gs"></a>
[75] K. Khawam, M. Ibrahim, J. Cohen, S. Lahoud, S. Tohme, **Individual vs. Global Radio Resource Management in a Hybrid Broadband Network**, *ICC 2011 Wireless Networking Symposium, ICC'11 WNS*, kyoto, Japan, 6 2011. [pdf](http://dl.dropbox.com/u/45967765/Publications/icc-11a.pdf)


<a id="salhi%3A2011ov"></a>
[76] E. Salhi, S. Lahoud, B. Cousin, **Heuristics for Joint Optimization of Monitor Location and Network Anomaly Detection**, *ICC 2011 Communications QoS, Reliability and Modeling Symposium (ICC'11 CQRM)*, Kyoto, Japan, 6 2011. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/icc-11b.pdf)


<a id="salhi%3A2011wq"></a>
[77] E. Salhi, S. Lahoud, B. Cousin, **Global Vs. Per-Domain Monitoring of Multi-Domain Networks**, *36th Annual IEEE Conference on Local Computer Networks (LCN 2011)*, Bonn, Germany, pp. 391 - 398, 2011. [doi](https://doi.org/10.1109/LCN.2011.6115321) [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/lcn-11b.pdf)


<a id="frikha%3A2011km"></a>
[78] A. Frikha, B. Cousin, S. Lahoud, **Extending node protection concept of p-cycles for an efficient resource utilization in multicast traffic**, *Local Computer Networks (LCN), 2011 IEEE 36th Conference on*, Bonn, Germany, pp. 175 -178, oct. 2011. [doi](https://doi.org/10.1109/LCN.2011.6115180) [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/lcn-11a.pdf)


<a id="jawhar%3A2011rw"></a>
[79] S. Jawhar, B. Cousin, S. Lahoud, **Effect of Splitting Factor on the Generated Multicast Trees in Optical Networks**, *International Conference on Network Communication and Computer (ICNCC 2011)*, New Delhi, India, pp. 127 - 130, 2011. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/icncc-11.pdf)


<a id="djarallah%3A2011dd"></a>
[80] N. Djarallah, N.L. Sauze, H. Pouyllau, S. Lahoud, B. Cousin, **Distributed E2E QoS-Based Path Computation Algorithm Over Multiple Inter-Domain Routes**, *Sixth International Conference on P2P, Parallel, Grid, Cloud and Internet Computing (3PGCIC 2011)*, BARCELONA, Spain, pp. 169 - 176, 2011. [doi](https://doi.org/10.1109/3PGCIC.2011.34) [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/3pgcic-11.pdf)


<a id="drid%3A2011zp"></a>
[81] H. Drid, L. Gonczy, S. Lahoud, G. Bergmann, M. Molnar, **Dependable Routing Protocol Considering the k-Coverage Problem for Wireless Sensor Networks**, *ICNS 2011: The Seventh International Conference on Networking and Services*, Venice, Italy, 2011. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/icns-11.pdf)


<a id="bellabas%3A2011rp"></a>
[82] A. Bellabas, G. Texier, S. Lahoud, A. Najah, **Convergent IPTV Services over IP Multimedia Subsystem**, *The 14th International Symposium on Wireless Personal Multimedia Communications (WPMC'11)*, Brest, France, 2011. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/wpmc-11.pdf)


<a id="frikha%3A2010yi"></a>
[83] A. Frikha, S. Lahoud, **Pre-computation based heuristic for inter-domain QoS routing**, *Fourth IEEE International Conference on Advanced Networks and Telecommunication Systems (ANTS) (IEEE ANTS 2010)*, Mumbai, India, pp. 61 -63, dec. 2010. [doi](https://doi.org/10.1109/ANTS.2010.5983529) [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/ants-10.pdf)


<a id="salhi%3A2010km"></a>
[84] E. Salhi, S. Lahoud, B. Cousin, **Joint Optimization of Monitor Location and Network Anomaly Detection**, *35th Annual IEEE Conference on Local Computer Networks, LCN 2010*, Denver, Colorado, USA, pp. 204-207, October 2010. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/lcn-10.pdf)


<a id="bellabas%3A2010yj"></a>
[85] A. Bellabas, S. Lahoud, M. Molnar, **Fast Heuristics for the QoS Multicast Routing Problem**, *IEEE Globecom 2010 - Communications QoS, Reliability and Modelling Symposium (GC10 - CQRM)*, Miami, Florida, USA, December 2010. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/globecom-10.pdf)


<a id="jawhar%3A2010hc"></a>
[86] S. Jawhar, B. Cousin, S. Lahoud, **Efficient Placement of Light Splitters for Heterogeneous Multicast Traffic in Optical Networks**, *High Capacity Optical Networks and Enabling Technologies (HONET)*, Cairo, Egypt, pp. 204 - 209, 2010. [doi](https://doi.org/10.1109/HONET.2010.5715774) [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/honet-10.pdf)


<a id="bellabas%3A2009mk"></a>
[87] A. Bellabas, G. Bertrand, S. Lahoud, G. Texier, M. Molnar, **Quality of Service Routing in Next Generation Networks**, *Colloque Francophone sur l'Ingenierie des Protocoles*, Strasbourg, France, 2009. [pdf](http://hal.inria.fr/inria-00538269/en/)


<a id="bellabas%3A2009yg"></a>
[88] A. Bellabas, M. Molnar, S. Lahoud, **Heuristiques pour le routage multicritère**, *MAnifestation des JEunes Chercheurs en Sciences et Technologies de l'Information et de la Communication*, Avigon, France, 2009. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/majecstic-09.pdf)


<a id="bellabas%3A2009tg"></a>
[89] A. Bellabas, M. Molnar, S. Lahoud, **Heuristics for the Multicriteria Routing Problem**, *Mosharaka International Conference on Communications Computers and Applications*, Amman, Jordan, 2009. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/miccca-09.pdf)


<a id="bertrand%3A2009qm"></a>
[90] G. Bertrand, S. Lahoud, G. Texier, M. Molnar, **Computation of Multi-Constrained Paths in Multi-Domain MPLS-TE Networks**, *Next Generation Internet Networks, NGI '09*, Aveiro, Portugal, pp. 1 -8, July 2009. [doi](https://doi.org/10.1109/NGI.2009.5175757) [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/ngi-09.pdf)


<a id="drid%3A2009fd"></a>
[91] H. Drid, S. Lahoud, B. Cousin, M. Molnar, **A Topology Aggregation Model for Survivability in Multi-Domain Optical Networks Using p-Cycles**, *Sixth IFIP Inter ional Conference on Network and Parallel Computing, 2009, NPC '09*, Gold Coast, Australia, pp. 211 -218, October 2009. [doi](https://doi.org/10.1109/NPC.2009.21) [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/npc-09.pdf)


<a id="drid%3A2008vp"></a>
[92] H. Drid, B. Cousin, S. Lahoud, M. Molnar, **Multi-criteria p-cycle network design**, *33rd IEEE Conference on Local Computer Networks, LCN 2008*, Montréal, Canada, pp. 361 -366, October 2008. [doi](https://doi.org/10.1109/LCN.2008.4664191) [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/lcn-08.pdf)


<a id="lahoud%3A2006rp"></a>
[93] S. Lahoud, G. Texier, L. Toutain, **Flow Allocation with Path Protection in Next Generation Internet Networks**, *IEEE International Conference on Communications, ICC '06*, Istanbul, Turkey, pp. 860 -865, June 2006. [doi](https://doi.org/10.1109/ICC.2006.254815) [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/icc-06.pdf)


<a id="lahoud%3A2006zl"></a>
[94] S. Lahoud, G. Texier, L. Toutain, **Approximation algorithm for minimum cost flow allocation with varied survivability**, *2nd Conference on Next Generation Internet Design and Engineering, NGI '06*, Valencia, Spain, pp. 8 pp. -299, 2006. [doi](https://doi.org/10.1109/NGI.2006.1678254) [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/ngi-06.pdf)


<a id="lahoud%3A2005ws"></a>
[95] S. Lahoud, G. Texier, L. Toutain, **Off-line Flow Allocation for Traffic Engineering in MPLS Networks**, *Third International Working Conference on Performance Modelling and Evaluation of Heterogeneous Networks, HET-NETs*, West Yorkshire, U.K, 2005. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/hetnets-05.pdf)


<a id="lahoud%3A2005sh"></a>
[96] S. Lahoud, **Fully polynomial approximation for survivable flow allocation with max-min fairness**, *CoNEXT '05: Proceedings of the 2005 ACM conference on Emerging network experiment and technology*, Toulouse, France, pp. 262–263, 2005. [doi](https://doi.org/10.1145/1095921.1095971) [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/conext-05.pdf)


<a id="lahoud%3A2005kv"></a>
[97] S. Lahoud, G. Texier, L. Toutain, **FATE: a polynomial time framework for flow allocation in MPLS-TE networks**, *The 14th IEEE Workshop on Local and Metropolitan Area Networks, LANMAN 2005*, Crete, Greece, pp. 6 pp. -6, September 2005. [doi](https://doi.org/10.1109/LANMAN.2005.1541532) [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/lanman-05.pdf)


<a id="lahoud%3A2004dg"></a>
[98] S. Lahoud, G. Texier, L. Toutain, **Serveur de Topologie OSPF**, *6èmes Journées Doctorales Informatique et Réseau, JDIR*, Lannion, France, 2004. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/jdir-04.pdf)


<a id="lahoud%3A2004ht"></a>
[99] S. Lahoud, G. Texier, L. Toutain, **Classification and Evaluation of Constraint-Based Routing Algorithms for MPLS Traffic Engineering**, *6èmes rencontres francophones sur les aspects algorithmiques des télécommunications, Algotel*, Batz-sur-mer, France, 2004. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/algotel-04.pdf)





## Book Chapters


<a id="maaz%3A2018dp"></a>
[1] B. Maaz, K. Khawam, S. Lahoud, J. Nasreddine, S. Tohme, **Achieving Spectral and Energy Efficiencies in Smart Cities Multi-cell Networks**, In *Information Innovation Technology in Smart Cities*, edited by L. Ismail, L. Zhang, Springer Singapore, Singapore, pp. 291–302, 2018. [doi](https://doi.org/10.1007/978-981-10-1741-4_19) [url](https://doi.org/10.1007/978-981-10-1741-4_19) [pdf](http://samer.lahoud.fr/pub-pdf/springer-18.pdf)


<a id="frikha%3A2011lc"></a>
[2] A. Frikha, S. Lahoud, B. Cousin, **Hybrid Inter-Domain QoS Routing with Crankback Mechanisms**, In *Smart Spaces and Next Generation Wired/Wireless Networking*, edited by S. Balandin, Y. Koucheryavy, H. Hu, Springer Berlin / Heidelberg, pp. 450-462, 2011. [doi](https://doi.org/10.1007/978-3-642-22875-9_41) [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/new2wan-11.pdf)


<a id="lahoud%3A2010kc"></a>
[3] S. Lahoud, **Réseaux locaux**, In *Technologies logicielles Architectures des systèmes*, edited by No Author, Techniques de l'ingénieur, 2010. [pdf](http://www.techniques-ingenieur.fr/base-documentaire/electronique-et-technologies-de-l-information-et-de-la-communication-th9/technologies-logicielles-architectures-des-systemes-ti402/reseaux-locaux-te7000/)


<a id="bertrand%3A2010vz"></a>
[4] G. Bertrand, S. Lahoud, G. Texier, M. Molnar, **QoS Routing and Management in Backbone Networks**, In *Intelligent Quality of Service Technologies and Network Management: Models for Enhancing Communication*, edited by P. Bhattarakosol, IGI Global, Hershey, Pennsylvania, USA, pp. 138-159, 2010. [doi](https://doi.org/10.4018/978-1-61520-791-6.ch008) [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/igi-10.pdf)


<a id="bertrand%3A2010kq"></a>
[5] G. Bertrand, S. Lahoud, G. Texier, M. Molnar, **Inter-Domain Path Computation with Multiple QoS Constraints**, In *Recent Advances in Providing QoS and Reliability in the Future Internet Backbone*, edited by N. Wang, G. Pavlou, M. Boucadair, Nova Science Publisher, 2010. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/nova-10.pdf)


<a id="bertrand%3A2009dt"></a>
[6] G. Bertrand, S. Lahoud, G. Texier, M. Molnar, **A Distributed Exact Solution to Compute Inter-domain Multi-constrained Paths**, In *The Internet of the Future*, edited by M. Oliver, S. Sallent, Springer Berlin, Heidelberg, Barcelona, Spain, pp. 21-30, 2009. [doi](https://doi.org/10.1007/978-3-642-03700-9_3) [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/eunice-09.pdf)













## Miscellaneous


<a id="Lahoud%3A2023az"></a>
[1] S. Lahoud, **Optimizing Resource Allocation in Cellular Wireless Networks**, Habilitation à diriger les recherches (HDR), 2023. [url](https://www.youtube.com/watch?v=oak98OLHk5c) [pdf](http://samer.lahoud.fr/pub-pdf/hdr-samerlahoud-24-2-23.pdf)


<a id="douville%3A2009lg"></a>
[2] R. Douville, S. Lahoud, **Path Computing Element Providing Customized Objective Function**, European Patent Application EP2066086, 2009. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/patent-objective-function.pdf)


<a id="lahoud%3A2009li"></a>
[3] S. Lahoud, R. Douville, **Method and Apparatus for Computing a Path in a Network**, European Patent Application EP2063585, 2009. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/patent-computing-path.pdf)




</div>

<div class="pub-view" data-view-panel="year">

## 2024


<a id="Khawam%3A2024lq-year"></a>
[1] K. Khawam, H. Taleb, S. Lahoud, H. Fawaz, D. Quadri, S. Martin, **Non-Cooperative Edge Server Selection Game for Federated Learning in IoT**, *NOMS 2024-2024 IEEE Network Operations and Management Symposium*, pp. 1-6, 2024. [doi](https://doi.org/10.1109/NOMS59830.2024.10575406)


<a id="Durand%3A2024fr-year"></a>
[2] S. Durand, K. Khawam, D. Quadri, S. Lahoud, S. Martin, **Federated Learning Game in IoT Edge Computing**, *IEEE Access*, vol. 12, pp. 93060-93074, 2024. [doi](https://doi.org/10.1109/ACCESS.2024.3420814)



## 2023


<a id="Loubany%3A2023yi-year"></a>
[1] A. Loubany, S. Lahoud, A.E. Samhat, M.E. Helou, **Throughput Improvement for LoRaWAN Networks Considering IoT Applications Priority**, *2023 6th Conference on Cloud and Internet of Things (CIoT)*, pp. 206-210, 2023. [doi](https://doi.org/10.1109/CIoT57267.2023.10084887)


<a id="Rayess%3A2023bf-year"></a>
[2] J.E. Rayess, K. Khawam, S. Lahoud, M.E. Helou, S. Martin, **Study of LoRaWAN Networks Reliability**, *2023 6th Conference on Cloud and Internet of Things (CIoT)*, pp. 200-205, 2023. [doi](https://doi.org/10.1109/CIoT57267.2023.10084880)


<a id="Rayess%3A2023km-year"></a>
[3] J.E. Rayess, K. Khawam, S. Lahoud, M.E. Helou, S. Martin, **RALI: Increasing Reliability in LoRaWAN through Repetition and Iteration**, *2023 IEEE Wireless Communications and Networking Conference (WCNC)*, pp. 1-6, 2023. [doi](https://doi.org/10.1109/WCNC55385.2023.10118962)


<a id="Fawaz%3A2023wu-year"></a>
[4] H. Fawaz, S. Lahoud, M.E. Helou, K. Khawam, **Queue-Aware Resource Allocation in Full-Duplex Multi-Cellular Wireless Networks**, *IEEE Journal on Selected Areas in Communications*, vol. 41, no. 9, pp. 2852-2863, 2023. [doi](https://doi.org/10.1109/JSAC.2023.3287541)


<a id="Lahoud%3A2023az-year"></a>
[5] S. Lahoud, **Optimizing Resource Allocation in Cellular Wireless Networks**, Habilitation à diriger les recherches (HDR), 2023. [url](https://www.youtube.com/watch?v=oak98OLHk5c) [pdf](http://samer.lahoud.fr/pub-pdf/hdr-samerlahoud-24-2-23.pdf)


<a id="Loubany%3A2023cq-year"></a>
[6] A. Loubany, S. Lahoud, A.E. Samhat, M. El Helou, **Joint throughput-energy optimization in multi-gateway LoRaWAN networks**, *Telecommunication Systems*, vol. 84, no. 2, pp. 271–283, 2023. [doi](https://doi.org/10.1007/s11235-023-01048-8) [url](https://doi.org/10.1007/s11235-023-01048-8)


<a id="Loubany%3A2023rg-year"></a>
[7] A. Loubany, S. Lahoud, A.E. Samhat, M. El Helou, **Improving Energy Efficiency in LoRaWAN Networks with Multiple Gateways**, *Sensors*, vol. 23, no. 11, 2023. [doi](https://doi.org/10.3390/s23115315) [url](https://www.mdpi.com/1424-8220/23/11/5315)


<a id="Loubany%3A2023bq-year"></a>
[8] A. Loubany, A.E. Samhat, S. Lahoud, M. El Helou, **Energy Efficiency Enhancement for LoRaWAN Networks with Multiple Gateways**, *2023 IEEE International Conference on Communications (ICC): IoT and Sensor Networks Symposium (IEEE ICC'23 - IoTSN Symposium)*, Rome, Italy, May 2023.


<a id="Khawam%3A2023ng-year"></a>
[9] K. Khawam, S. Lahoud, C. Adjih, S. Makhoul, R. Al Tawil, S. Martin, **Edge Learning as a Hedonic Game in LoRaWAN**, *2023 IEEE International Conference on Communications (ICC): IoT and Sensor Networks Symposium (IEEE ICC'23 - IoTSN Symposium)*, Rome, Italy, May 2023.


<a id="Awada%3A2023le-year"></a>
[10] Z. Awada, M. El Helou, K. Khawam, S. Lahoud, **Dynamic Multi-Tenant RAN Slicing for eMBB, URLLC, and mMTC in 5G Networks**, *2023 26th International Symposium on Wireless Personal Multimedia Communications (WPMC)*, pp. 1-7, 2023. [doi](https://doi.org/10.1109/WPMC59531.2023.10338951)


<a id="Awada%3A2023dw-year"></a>
[11] Z. Awada, K. Khawam, S. Lahoud, M. El Helou, **A Stackelberg Game for Multi-Tenant RAN Slicing in 5G Networks**, *2023 IEEE Symposium on Computers and Communications (ISCC)*, pp. 1058-1061, 2023. [doi](https://doi.org/10.1109/ISCC58397.2023.10218208)


<a id="Iskandarani%3A2023jy-year"></a>
[12] H. Iskandarani, H.Y. Kanaan, M. Helou, K. Khawam, S. Lahoud, K. Al-Haddad, **A Neural-Network-Based Controller for a Three- Phase Dual-Active-Bridge DC-DC Converter**, *2023 IEEE Conference on Power Electronics and Renewable Energy (CPERE)*, pp. 1-7, 2023. [doi](https://doi.org/10.1109/CPERE56564.2023.10119632)


<a id="Awada%3A2023vf-year"></a>
[13] Z. Awada, M. El Helou, K. Khawam, S. Lahoud, **A Multi-Armed Bandit Game for Multi-Tenant RAN Slicing**, *2023 IEEE 4th International Multidisciplinary Conference on Engineering Technology (IMCET)*, pp. 62-68, 2023. [doi](https://doi.org/10.1109/IMCET59736.2023.10368268)


<a id="Yassine%3A2023sr-year"></a>
[14] F. Yassine, M.E. Helou, S. Lahoud, O. Bazzi, **A Four-Sided Matching Game for Energy-Efficient Scheduling in Narrowband-IoT Networks**, *IEEE Access*, vol. 11, pp. 44482-44495, 2023. [doi](https://doi.org/10.1109/ACCESS.2023.3266443)



## 2022


<a id="Taleb%3A2022zr-year"></a>
[1] H. Taleb, K. Khawam, S. Lahoud, M.E. Helou, S. Martin, **Pilot Contamination Mitigation in Massive MIMO Cloud Radio Access Networks**, *IEEE Access*, vol. 10, pp. 58212-58224, 2022. [doi](https://doi.org/10.1109/ACCESS.2022.3177629)


<a id="Yassine%3A2022sf-year"></a>
[2] F. Yassine, M. El Helou, S. Lahoud, O. Bazzi, **Energy-Efficient Uplink Scheduling in Narrowband IoT**, *Sensors*, vol. 22, no. 20, 2022. [doi](https://doi.org/10.3390/s22207744) [url](https://www.mdpi.com/1424-8220/22/20/7744)


<a id="Awada%3A2022hc-year"></a>
[3] Z. Awada, K. Boulos, M. El-Helou, K. Khawam, S. Lahoud, **Distributed multi-tenant RAN slicing in 5G networks**, *Wireless Networks*, 2022. [doi](https://doi.org/10.1007/s11276-022-03023-8) [url](https://doi.org/10.1007/s11276-022-03023-8)


<a id="Loubany%3A2022if-year"></a>
[4] A. Loubany, A.E. Samhat, S. Lahoud, M.E. Helou, **Battery-Less LoRaWAN Network using Energy Harvesting: Improving Network Throughput**, *2022 IEEE 33rd Annual International Symposium on Personal, Indoor and Mobile Radio Communications (PIMRC)*, pp. 1032-1037, 2022. [doi](https://doi.org/10.1109/PIMRC54779.2022.9977716)


<a id="Khawam%3A2022wd-year"></a>
[5] K. Khawam, H. Fawaz, S. Lahoud, O. Maillard, S. Martin, **A channel selection game for multi-operator LoRaWAN deployments**, *Computer Networks*, vol. 216, pp. 109185, 2022. [doi](https://doi.org/10.1016/j.comnet.2022.109185) [url](https://www.sciencedirect.com/science/article/pii/S1389128622002821)



## 2021


<a id="Yassine%3A2021bh-year"></a>
[1] F. Yassine, M. El Helou, S. Lahoud, O. Bazzi, **Performance of Narrowband IoT Link Adaptation with Rate and Energy Objectives**, *2021 IEEE 3rd International Multidisciplinary Conference on Engineering Technology (IMCET)*, pp. 6-10, 2021. [doi](https://doi.org/10.1109/IMCET53404.2021.9665562)


<a id="Fawaz%3A2021pi-year"></a>
[2] H. Fawaz, K. Khawam, S. Lahoud, C. Adjih, S. Martin, **Joint Spreading Factor and Channel Assignment in Multi-Operator LoRaWAN Deployments**, *Sensors*, vol. 21, no. 1, 2021. [doi](https://doi.org/10.3390/s21010162) [pdf](http://samer.lahoud.fr/pub-pdf/sensors-21.pdf)


<a id="Yassine%3A2021pd-year"></a>
[3] F. Yassine, M.E. Helou, O. Bazzi, S. Lahoud, **Investigation on Narrowband IoT Link Adaptation with Rate and Energy Objectives**, *2021 International Wireless Communications and Mobile Computing (IWCMC)*, pp. 412-417, 2021. [doi](https://doi.org/10.1109/IWCMC51323.2021.9498738)


<a id="Ayoub%3A2021mz-year"></a>
[4] I. Ayoub, I. Hmedoush, C. Adjih, K. Khawam, S. Lahoud, **Deep-IRSA: A Deep Reinforcement Learning Approach to Irregular Repetition Slotted ALOHA**, *2021 10th IFIP International Conference on Performance Evaluation and Modeling in Wireless and Wired Networks (PEMWN)*, pp. 1-6, 2021. [doi](https://doi.org/10.23919/PEMWN53042.2021.9664720)


<a id="Fawaz%3A2021jt-year"></a>
[5] H. Fawaz, M. El Helou, S. Lahoud, K. Khawam, **A reinforcement learning approach to queue-aware scheduling in full-duplex wireless networks**, *Computer Networks*, vol. 189, pp. 107893, 2021. [doi](https://doi.org/10.1016/j.comnet.2021.107893) [pdf](http://samer.lahoud.fr/pub-pdf/comnet-21.pdf)



## 2020


<a id="Lahad%3A2020ph-year"></a>
[1] B. Lahad, M. Ibrahim, S. Lahoud, K. Khawam, S. Martin, **Uplink/Downlink Decoupled Access with Dynamic TDD in 5G HetNets**, *2020 International Wireless Communications and Mobile Computing (IWCMC)*, pp. 1330-1335, 2020. [doi](https://doi.org/10.1109/IWCMC48107.2020.9148375) [pdf](http://samer.lahoud.fr/pub-pdf/iwcmc-20.pdf)


<a id="Fawaz%3A2020uo-year"></a>
[2] H. Fawaz, S. Lahoud, M. El Helou, **Queue-aware scheduling in full-duplex wireless networks**, *Wireless Networks*, 2020. [doi](https://doi.org/10.1007/s11276-020-02308-0) [pdf](http://samer.lahoud.fr/pub-pdf/wireless-20.pdf)


<a id="Martinez%3A2020cs-year"></a>
[3] I. Martinez, F. Nouvel, S. Lahoud, P. Tanguy, M.E. Helou, **On the Performance Evaluation of LoRaWAN with Re-transmissions under Jamming**, *2020 IEEE Symposium on Computers and Communications (ISCC)*, pp. 1-7, 2020. [doi](https://doi.org/10.1109/ISCC50000.2020.9219644) [pdf](http://samer.lahoud.fr/pub-pdf/iscc-20.pdf)


<a id="Lahad%3A2020qq-year"></a>
[4] B. Lahad, M. Ibrahim, S. Lahoud, K. Khawam, S. Martin, **Joint Modeling of TDD and Decoupled Uplink/Downlink Access in 5G HetNets with Multiple Small Cells Deployment**, *IEEE Transactions on Mobile Computing*, pp. 1-1, 2020. [doi](https://doi.org/10.1109/TMC.2020.2979447) [pdf](http://samer.lahoud.fr/pub-pdf/tmc-20a.pdf)


<a id="Khawam%3A2020ek-year"></a>
[5] K. Khawam, S. Lahoud, M. El Helou, S. Martin, G. Feng, **Coordinated Framework for Spectrum Allocation and User Association in 5G HetNets with mmWave**, *IEEE Transactions on Mobile Computing*, pp. 1-1, 2020. [doi](https://doi.org/10.1109/TMC.2020.3022681) [pdf](http://samer.lahoud.fr/pub-pdf/tmc-20b.pdf)


<a id="Fawaz%3A2020la-year"></a>
[6] H. Fawaz, K. Khawam, S. Lahoud, S. Martin, M. El Helou, **Cooperation for Spreading Factor Assignment in a Multi-Operator LoRaWAN Deployment**, *IEEE Internet of Things Journal*, pp. 1-1, 2020. [doi](https://doi.org/10.1109/JIOT.2020.3031681) [pdf](http://samer.lahoud.fr/pub-pdf/iotj-20.pdf)


<a id="Loubany%3A2020gd-year"></a>
[7] A. Loubany, S. Lahoud, R. El Chall, **Adaptive algorithm for spreading factor selection in LoRaWAN networks with multiple gateways**, *Computer Networks*, vol. 182, pp. 107491, 2020. [doi](https://doi.org/10.1016/j.comnet.2020.107491) [pdf](http://samer.lahoud.fr/pub-pdf/comnet-20b.pdf)


<a id="Taleb%3A2020it-year"></a>
[8] H. Taleb, K. Khawam, S. Lahoud, M.E. Helou, S. Martin, **A fully distributed approach for joint user association and RRH clustering in cloud radio access networks**, *Computer Networks*, vol. 182, pp. 107445, 2020. [doi](https://doi.org/10.1016/j.comnet.2020.107445) [pdf](http://samer.lahoud.fr/pub-pdf/comnet-20a.pdf)



## 2019


<a id="el-chall%3A2019qy-year"></a>
[1] R. El Chall, S. Lahoud, M. El Helou, **LoRaWAN Network: Radio Propagation Models and Performance Evaluation in Various Environments in Lebanon**, *IEEE Internet of Things Journal*, pp. 1-1, 2019. [doi](https://doi.org/10.1109/JIOT.2019.2906838) [pdf](http://samer.lahoud.fr/pub-pdf/jiot-19.pdf)


<a id="Ta%3A2019eu-year"></a>
[2] D. Ta, K. Khawam, S. Lahoud, C. Adjih, S. Martin, **LoRa-MAB: Toward an Intelligent Resources Allocation Approach for LoRaWAN Networks**, *2019 IEEE Global Communications Conference: Selected Areas in Communications: Internet of Things (Globecom2019 SAC IoT)*, Waikoloa, USA, December 2019. [pdf](http://samer.lahoud.fr/pub-pdf/globecom-19.pdf)


<a id="Ta%3A2019yg-year"></a>
[3] D. Ta, K. Khawam, S. Lahoud, C. Adjih, S. Martin, **LoRa-MAB: A Flexible Simulator for Decentralized Learning Resource Allocation in IoT Networks**, *2019 12th IFIP Wireless and Mobile Networking Conference (WMNC)*, pp. 55-62, Sep. 2019. [doi](https://doi.org/10.23919/WMNC.2019.8881393) [pdf](http://samer.lahoud.fr/pub-pdf/wmnc-19.pdf)


<a id="ben-dhia%3A2019uq-year"></a>
[4] I. Ben Dhia, M. Bouhtou, T. En-Najjary, S. Lahoud, X. Lagrange, **Dynamic Access Point Selection and Resource Allocation in Multi-Technology Wireless Network**, *2019 IEEE Wireless Communications and Networking Conference (WCNC) (IEEE WCNC 2019)*, Marrakech, Morocco, April 2019. [pdf](http://samer.lahoud.fr/pub-pdf/wcnc-19.pdf)


<a id="Fawaz%3A2019wd-year"></a>
[5] H. Fawaz, K. Khawam, S. Lahoud, M. El Helou, **A Game Theoretic Framework for Power Allocation in Full-Duplex Wireless Networks**, *IEEE Access*, vol. 7, pp. 174013-174027, 2019. [doi](https://doi.org/10.1109/ACCESS.2019.2957316) [pdf](http://samer.lahoud.fr/pub-pdf/access-19.pdf)


<a id="Fawaz%3A2019fv-year"></a>
[6] H. Fawaz, K. Khawam, S. Lahoud, M. El Helou, **A Game Theoretic Approach for Power Allocation in Full Duplex Wireless Networks**, *2019 IEEE 30th Annual International Symposium on Personal, Indoor and Mobile Radio Communications (PIMRC): Track 3: Mobile and Wireless Networks (IEEE PIMRC 2019 - Track 3)*, Istanbul, Turkey, September 2019. [pdf](http://samer.lahoud.fr/pub-pdf/pimrc-19.pdf)



## 2018


<a id="fawaz%3A2018rt-year"></a>
[1] H. Fawaz, S. Lahoud, M. El Helou, M. Ibrahim, **Queue-Aware Scheduling in Full Duplex OFDMA Wireless Networks with Imperfect Channel State Information**, *European Wireless 2018 (EW 2018)*, Catania, Italy, May 2018. [pdf](http://samer.lahoud.fr/pub-pdf/ew-18.pdf)


<a id="fawaz%3A2018ly-year"></a>
[2] H. Fawaz, S. Lahoud, M. El Helou, J. Saad, **Queue-Aware Priority Based Scheduling and Power Allocation in Full-Duplex OFDMA Cellular Networks**, *2018 25th International Conference on Telecommunications (ICT) (ICT 2018)*, Saint Malo, France, June 2018. [pdf](http://samer.lahoud.fr/pub-pdf/ict-a-18.pdf)


<a id="fawaz%3A2018vn-year"></a>
[3] H. Fawaz, S. Lahoud, M. El Helou, M. Ibrahim, **Optimal Max-SINR Scheduling in Full-Duplex OFDMA Cellular Networks with Dynamic Arrivals**, *2018 Wireless Days (WD) (WD'18)*, Dubai, United Arab Emirates, April 2018. [pdf](http://samer.lahoud.fr/pub-pdf/wd-18.pdf)


<a id="taleb%3A2018qf-year"></a>
[4] H. Taleb, S. Lahoud, K. Khawam, M. El Helou, S. Martin, **Multi-objective Optimization for RRH clustering in Cloud Radio Access Networks**, *2018 International Conference on Computer and Applications (ICCA) (ICCA-18)*, Beirut, Lebanon, July 2018. [pdf](http://samer.lahoud.fr/pub-pdf/icca-b-18.pdf)


<a id="taleb%3A2018ul-year"></a>
[5] H. Taleb, M. El Helou, K. Khawam, S. Lahoud, S. Martin, **Joint User Association and RRH Clustering in Cloud Radio Access Networks**, *2018 Tenth International Conference on Ubiquitous and Future Networks (ICUFN) (ICUFN 2018)*, Prague, Czech Republic, July 2018. [pdf](http://samer.lahoud.fr/pub-pdf/icufn-18.pdf)


<a id="lahad%3A2018pd-year"></a>
[6] B. Lahad, M. Ibrahim, S. Lahoud, K. Khawam, S. Martin, **Analytical Evaluation of Decoupled Uplink and Downlink Access in TDD 5G HetNets**, *2018 IEEE 29th Annual International Symposium on Personal, Indoor and Mobile Radio Communications (PIMRC) (IEEE PIMRC 2018)*, Bologna, Italy, September 2018. [pdf](http://samer.lahoud.fr/pub-pdf/pimrc-18.pdf)


<a id="taleb%3A2018gf-year"></a>
[7] H. Taleb, M. El Helou, S. Lahoud, K. Khawam, S. Martin, **An Efficient Heuristic for Joint User Association and RRH Clustering in Cloud Radio Access Networks**, *2018 25th International Conference on Telecommunications (ICT) (ICT 2018)*, Saint Malo, France, June 2018. [pdf](http://samer.lahoud.fr/pub-pdf/ict-b-18.pdf)


<a id="maaz%3A2018dp-year"></a>
[8] B. Maaz, K. Khawam, S. Lahoud, J. Nasreddine, S. Tohme, **Achieving Spectral and Energy Efficiencies in Smart Cities Multi-cell Networks**, In *Information Innovation Technology in Smart Cities*, edited by L. Ismail, L. Zhang, Springer Singapore, Singapore, pp. 291–302, 2018. [doi](https://doi.org/10.1007/978-981-10-1741-4_19) [url](https://doi.org/10.1007/978-981-10-1741-4_19) [pdf](http://samer.lahoud.fr/pub-pdf/springer-18.pdf)


<a id="lahad%3A2018ys-year"></a>
[9] B. Lahad, M. Ibrahim, K. Khawam, S. Martin, S. Lahoud, **A Statistical Model for Uplink/Downlink Intercell Interference and Cell Capacity in TDD HetNets**, *IEEE ICC 2018 Wireless Communications Symposium (ICC'18 WCS)*, Kansas City, USA, May 2018. [pdf](http://samer.lahoud.fr/pub-pdf/icc-18.pdf)


<a id="fawaz%3A2018ve-year"></a>
[10] H. Fawaz, S. Lahoud, M. El Helou, **A Queue-Aware Discrete Scheduling Simulator for Full-Duplex OFDMA Wireless Networks**, *2018 International Conference on Computer and Applications (ICCA) (ICCA-18)*, Beirut, Lebanon, July 2018. [pdf](http://samer.lahoud.fr/pub-pdf/icca-a-18.pdf)



## 2017


<a id="said%3A2017ij-year"></a>
[1] S.B.H. Said, B. Cousin, S. Lahoud, **Software defined networking (SDN) for reliable user connectivity in 5G networks**, *2017 IEEE Conference on Network Softwarization (NetSoft)*, pp. 1-5, July 2017. [doi](https://doi.org/10.1109/NETSOFT.2017.8004219) [pdf](http://samer.lahoud.fr/pub-pdf/netsoft-17.pdf)


<a id="farhat%3A2017fk-year"></a>
[2] S. Farhat, A.E. Samhat, S. Lahoud, B. Cousin, **Radio Access Network Sharing in 5G: Strategies and Benefits**, *Wireless Personal Communications*, 2017. [doi](https://doi.org/10.1007/s11277-017-4321-1) [pdf](http://samer.lahoud.fr/pub-pdf/wpc-17.pdf)


<a id="dhia%3A2017sp-year"></a>
[3] I.B. Dhia, M. Bouhtou, T. En-Najjary, S. Lahoud, X. Lagrange, **Optimization of access points selection and resource allocation in heterogeneous wireless network**, *2017 IEEE 28th Annual International Symposium on Personal, Indoor, and Mobile Radio Communications (PIMRC)*, pp. 1-7, Oct 2017. [doi](https://doi.org/10.1109/PIMRC.2017.8292261) [pdf](http://samer.lahoud.fr/pub-pdf/pimrc-17.pdf)


<a id="fawaz%3A2017ve-year"></a>
[4] H. Fawaz, S. Lahoud, M. El Helou, M. Ibrahim, **On Scheduling in Full-Duplex OFDMA Cellular Networks**, *23th LAAS International Science Conference (LAAS'17)*, Kaslik, Lebanon, pp. 52-53, April 2017. [pdf](http://samer.lahoud.fr/pub-pdf/laas-17.pdf)


<a id="fawaz%3A2017ul-year"></a>
[5] H. Fawaz, S. Lahoud, M. Ibrahim, M. El Helou, **Max-SINR Scheduling in Full-Duplex OFDMA Cellular Networks with Dynamic Arrivals**, *2017 IEEE Symposium on Computers and Communications (ISCC) (ISCC 2017)*, Heraklion, Greece, pp. 493-498, July 2017. [pdf](http://samer.lahoud.fr/pub-pdf/iscc-17b.pdf)


<a id="maaz%3A2017ly-year"></a>
[6] B. Maaz, K. Khawam, S. Lahoud, J. Nasreddine, S. Tohme, **Joint User Association, Power Control and Scheduling in Multi-Cell 5G Networks**, *2017 IEEE Wireless Communications and Networking Conference (WCNC) (IEEE WCNC 2017)*, San Francisco, USA, March 2017. [pdf](http://samer.lahoud.fr/pub-pdf/wcnc-17.pdf)


<a id="rabah%3A2017gf-year"></a>
[7] G. Rabah, O.D. Dugeon, S. Lahoud, G. Texier, **Demonstration of Segment Routing with SDN Based Label Stack Optimization**, *2017 20th Conference on Innovations in Clouds, Internet and Networks (ICIN) (ICIN 2017)*, Paris, France, pp. 143-145, March 2017. [pdf](http://samer.lahoud.fr/pub-pdf/icin-17.pdf)


<a id="yassin%3A2017xr-year"></a>
[8] M. Yassin, S. Lahoud, M. Ibrahim, K. Khawam, D. Mezher, B. Cousin, **Cooperative resource management and power allocation for multiuser OFDMA networks**, *IET Communications*, vol. 11, no. 16, pp. 2552-2559, 2017. [doi](https://doi.org/10.1049/iet-com.2017.0201) [pdf](http://samer.lahoud.fr/pub-pdf/iet-17.pdf)


<a id="yassin%3A2017mz-year"></a>
[9] M. Yassin, S. Lahoud, K. Khawam, M. Ibrahim, D. Mezher, B. Cousin, **Centralized versus decentralized multi-cell resource and power allocation for multiuser OFDMA networks**, *Computer Communications*, vol. 107, pp. 112 - 124, 2017. [doi](https://doi.org/10.1016/j.comcom.2017.04.002) [pdf](http://samer.lahoud.fr/pub-pdf/comcom-17.pdf)


<a id="taleb%3A2017qf-year"></a>
[10] H. Taleb, K. Khawam, S. Lahoud, M. El Helou, S. Martin, **Centralized and Distributed RRH Clustering in Cloud Radio Access Networks**, *2017 IEEE Symposium on Computers and Communications (ISCC) (ISCC 2017)*, Heraklion, Greece, pp. 1094-1100, July 2017. [pdf](http://samer.lahoud.fr/pub-pdf/iscc-17a.pdf)


<a id="maaz%3A2017rt-year"></a>
[11] B. Maaz, K. Khawam, J. Nasreddine, S. Lahoud, S. Tohme, **Achieving Power and Energy Efficiency in Self-Organizing Networks**, *2017 14th IEEE Annual Consumer Communications & Networking Conference (CCNC) (CCNC 2017)*, Las Vegas, USA, January 2017. [pdf](http://samer.lahoud.fr/pub-pdf/ccnc-17.pdf)


<a id="guedrez%3A2017hc-year"></a>
[12] R. Guedrez, O. Dugeon, S. Lahoud, G. Texier, **A new method for encoding MPLS segment routing TE paths**, *2017 8th International Conference on the Network of the Future (NOF)*, pp. 58-65, Nov 2017. [doi](https://doi.org/10.1109/NOF.2017.8251221) [pdf](http://samer.lahoud.fr/pub-pdf/nof-17.pdf)



## 2016


<a id="khawam%3A2016uq-year"></a>
[1] K. Khawam, S. Lahoud, M. Ibrahim, M. Yassin, S. Martin, M.E. Helou, F. Moety, **Radio access technology selection in heterogeneous networks**, *Physical Communication*, vol. 18, Part 2, pp. 125 - 139, 2016. [doi](https://doi.org/10.1016/j.phycom.2015.10.004) [pdf](http://samer.lahoud.fr/pub-pdf/phycom-15.pdf)


<a id="guedrez%3A2016yq-year"></a>
[2] R. Guedrez, O. Dugeon, S. Lahoud, G. Texier, **Label encoding algorithm for MPLS Segment Routing**, *2016 IEEE 15th International Symposium on Network Computing and Applications (NCA)*, pp. 113-117, Oct 2016. [doi](https://doi.org/10.1109/NCA.2016.7778603) [pdf](http://samer.lahoud.fr/pub-pdf/nca-16.pdf)


<a id="maaz%3A2016vn-year"></a>
[3] B. Maaz, K. Khawam, Y. Hayel, S. Lahoud, S. Martin, D. Quadri, **Joint user association, scheduling and power control in multi-cell networks**, *2016 IEEE 12th International Conference on Wireless and Mobile Computing, Networking and Communications (WiMob)*, pp. 1-7, Oct 2016. [doi](https://doi.org/10.1109/WiMOB.2016.7763205) [pdf](http://samer.lahoud.fr/pub-pdf/wimob-16.pdf)


<a id="lahoud%3A2016kx-year"></a>
[4] S. Lahoud, K. Khawam, S. Martin, G. Feng, Z. Liang, J. Nasreddine, **Energy Efficient Joint Scheduling and Power Control in Multi-Cell Wireless Networks**, *IEEE Journal on Selected Areas in Communications*, vol. PP, no. 99, pp. 1-1, 2016. [doi](https://doi.org/10.1109/JSAC.2016.2611847) [pdf](http://samer.lahoud.fr/pub-pdf/jsac-16.pdf)


<a id="yassin%3A2016uq-year"></a>
[5] M. Yassin, S. Lahoud, M. Ibrahim, K. Khawam, D. Mezher, B. Cousin, **Centralized multi-cell resource and power allocation for multiuser OFDMA networks**, *2016 IFIP Networking Conference (IFIP Networking) and Workshops*, pp. 162-170, May 2016. [doi](https://doi.org/10.1109/IFIPNetworking.2016.7497211) [pdf](http://samer.lahoud.fr/pub-pdf/networking-16.pdf)


<a id="el-helou%3A2016qy-year"></a>
[6] M. El Helou, S. Lahoud, M. Ibrahim, K. Khawam, B. Cousin, D. Mezher, **A Hybrid Approach for Radio Access Technology Selection in Heterogeneous Wireless Networks**, *Wireless Personal Communications*, vol. 86, no. 2, pp. 789–834, 2016. [doi](https://doi.org/10.1007/s11277-015-2957-2) [pdf](https://hal.archives-ouvertes.fr/hal-01182891)



## 2015


<a id="yassin%3A2015fi-year"></a>
[1] M. Yassin, M.A. AboulHassan, S. Lahoud, M. Ibrahim, D. Mezher, B. Cousin, E.A. Sourour, **Survey of ICIC Techniques in LTE Networks under Various Mobile Environment Parameters**, *Wireless Networks*, pp. 1, 2015. [url](https://hal.archives-ouvertes.fr/hal-01198389) [pdf](https://hal.archives-ouvertes.fr/hal-01198389/file/2015_09_12_HAL_Survey_of_ICIC_Techniques_in_LTE_Networks_under_Various_Mobile_Environment_Parameters.pdf)


<a id="boulos%3A2015zv-year"></a>
[2] K. Boulos, M. El Helou, S. Lahoud, **RRH clustering in cloud radio access networks**, *Applied Research in Computer Science and Engineering (ICAR), 2015 International Conference on*, pp. 1-6, Oct 2015. [doi](https://doi.org/10.1109/ARCSE.2015.7338135) [pdf](http://samer.lahoud.fr/pub-pdf/icar-15a.pdf)


<a id="farhat%3A2015sw-year"></a>
[3] S. Farhat, A.E. Samhat, S. Lahoud, B. Cousin, **Pricing Strategies in Multi-Operator Heterogeneous Wireless Networks**, *NTMS'2015 - Mobility & Wireless Networks Track (NTMS'2015 Mobility & Wireless Networks Track)*, Paris, France, July 2015. [pdf](http://samer.lahoud.fr/pub-pdf/ntms-15a.pdf)


<a id="moety%3A2015sj-year"></a>
[4] F. Moety, S. Lahoud, B. Cousin, K. Khawam, **Optimization models for the joint Power-Delay minimization problem in green wireless access networks**, *Computer Networks*, vol. 92, Part 1, pp. 148 - 167, 2015. [doi](https://doi.org/10.1016/j.comnet.2015.09.032) [pdf](http://samer.lahoud.fr/pub-pdf/comnet-15.pdf)


<a id="yassin%3A2015xd-year"></a>
[5] M. Yassin, S. Lahoud, M. Ibrahim, K. Khawam, D. Mezher, B. Cousin, **Non-Cooperative Inter-Cell Interference Coordination Technique for Increasing Throughput Fairness in LTE Networks**, *VTC Spring 2015*, 2015. [pdf](http://samer.lahoud.fr/pub-pdf/vtc-15.pdf)


<a id="maaz%3A2015qy-year"></a>
[6] B. Maaz, K. Khawam, S. Tohme, S. Martin, S. Lahoud, J. Nasreddine, **Joint scheduling and power control in multi-cell networks for inter-cell interference coordination**, *Wireless and Mobile Computing, Networking and Communications (WiMob), 2015 IEEE 11th International Conference on*, pp. 778-785, Oct 2015. [doi](https://doi.org/10.1109/WiMOB.2015.7348041) [pdf](http://samer.lahoud.fr/pub-pdf/wimob-15.pdf)


<a id="maaz%3A2015px-year"></a>
[7] B. Maaz, K. Khawam, S. Tohme, S. Lahoud, J. Nasreddine, **Inter-cell interference coordination based on power control for self-organized 4G systems**, *Digital Information and Communication Technology and its Applications (DICTAP), 2015 Fifth International Conference on*, pp. 149-154, April 2015. [doi](https://doi.org/10.1109/DICTAP.2015.7113188) [pdf](http://samer.lahoud.fr/pub-pdf/dictap-15b.pdf)


<a id="farhat%3A2015hs-year"></a>
[8] S. Farhat, A. Samhat, S. Lahoud, B. Cousin, **Comparison between access selection algorithms in multi-operator wireless networks**, *Applied Research in Computer Science and Engineering (ICAR), 2015 International Conference on*, pp. 1-8, Oct 2015. [doi](https://doi.org/10.1109/ARCSE.2015.7338132) [pdf](http://samer.lahoud.fr/pub-pdf/icar-15b.pdf)


<a id="aboulhassan%3A2015et-year"></a>
[9] M.A. AboulHassan, M. Yassin, S. Lahoud, M. Ibrahim, D. Mezher, B. Cousin, E. Sourour, **Classification and Comparative Analysis of Inter-Cell Interference Coordination Techniques in LTE Networks**, *NTMS'2015 - Mobility & Wireless Networks Track (NTMS'2015 Mobility & Wireless Networks Track)*, Paris, France, July 2015. [pdf](http://samer.lahoud.fr/pub-pdf/ntms-15b.pdf)


<a id="farhat%3A2015fh-year"></a>
[10] S. Farhat, Z. Chahine, A. Samhat, S. Lahoud, B. Cousin, **Access selection and joint pricing in multi-operator wireless networks: A Stackelberg game**, *Digital Information and Communication Technology and its Applications (DICTAP), 2015 Fifth International Conference on*, pp. 38-43, April 2015. [doi](https://doi.org/10.1109/DICTAP.2015.7113167) [pdf](http://samer.lahoud.fr/pub-pdf/dictap-15a.pdf)


<a id="yassin%3A2015lo-year"></a>
[11] M. Yassin, Y. Dirani, M. Ibrahim, S. Lahoud, D. Mezher, B. Cousin, **A Novel Dynamic Inter-Cell Interference Coordination Technique for LTE Networks**, *2015 IEEE 26th International Symposium on Personal, Indoor and Mobile Radio Communications - (PIMRC): Mobile and Wireless Networks (IEEE PIMRC2015 Mobile & Wireless)*, Hong Kong, P.R. China, pp. 1742-1747, August 2015. [pdf](http://samer.lahoud.fr/pub-pdf/pimrc-15.pdf)


<a id="el-helou%3A2015cr-year"></a>
[12] M. El Helou, M. Ibrahim, S. Lahoud, K. Khawam, D. Mezher, B. Cousin, **A Network-Assisted Approach for RAT Selection in Heterogeneous Cellular Networks**, *IEEE Journal on Selected Areas in Communications - Special Issue on Recent Advances in Heterogenous Cellular Networks (JSAC - HCN)*, vol. 33, no. 6, pp. 1055-1067, June 2015. [doi](https://doi.org/10.1109/JSAC.2015.2416987) [pdf](http://samer.lahoud.fr/pub-pdf/jsac-15.pdf)


<a id="moety%3A2015pr-year"></a>
[13] F. Moety, S. Lahoud, B. Cousin, K. Khawam, **A Heuristic Algorithm for Joint Power-Delay Minimization in Green Wireless Access Networks**, *2015 International Conference on Computing, Networking and Communications (ICNC), Workshop on Computing, Networking and Communications (CNC) (ICNC'15 CNC Workshop)*, Anaheim, USA, February 2015. [pdf](http://samer.lahoud.fr/pub-pdf/cnc-14.pdf)



## 2014


<a id="el-helou%3A2014bx-year"></a>
[1] M. El Helou, M. Ibrahim, S. Lahoud, K. Khawam, **Optimizing Network Information for Radio Access Technology Selection**, *19th IEEE Symposium on Computers and Communications (IEEE ISCC 2014)*, Madeira, Portugal, June 2014. [pdf](http://samer.lahoud.fr/pub-pdf/iscc-14.pdf)


<a id="djarallah%3A2014fb-year"></a>
[2] N. Djarallah, H. Pouyllau, S. Lahoud, B. Cousin, **Multi-Constrained Path Computation for Inter-Domain QoS-capable Services**, *International Journal of Communication Networks and Distributed Systems*, vol. 12, pp. 1-22, 2014. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/ijcnds-12.pdf)


<a id="moety%3A2014le-year"></a>
[3] F. Moety, S. Lahoud, B. Cousin, K. Khawam, **Joint Power-Delay Minimization in 4G Wireless Networks**, *2014 Wireless Days conference (WD'14)*, Rio de Janeiro, Brazil, November 2014. [pdf](http://samer.lahoud.fr/pub-pdf/wd-14.pdf)


<a id="farhat%3A2014ya-year"></a>
[4] S. Farhat, A.E. Samhat, S. Lahoud, **Hybrid Decision Algorithm for Access Selection in Multi-Operator Networks**, *IEEE WCNC'14 Track 3 (Mobile and Wireless Networks) (IEEE WCNC'14 Track 3 : NET)*, Istanbul, Turkey, April 2014. [pdf](http://samer.lahoud.fr/pub-pdf/wcnc-14.pdf)


<a id="khawam%3A2014wb-year"></a>
[5] K. Khawam, A. Adouane, S. Lahoud, S. Tohme, J. Cohen, **Game Theoretic Framework for Power Control in InterCell Interference Coordination**, *IFIP Networking 2014 Conference (Networking 2014)*, Trondheim, Norway, June 2014. [pdf](http://samer.lahoud.fr/pub-pdf/networking-14.pdf)


<a id="belghith%3A2014xz-year"></a>
[6] A. Belghith, B. Cousin, S. Lahoud, **Configurable Monitoring For Multi-Domain Networks**, *International Journal of Modern Engineering Research*, vol. 4, no. 2, pp. 65-89, February 2014. [pdf](http://samer.lahoud.fr/pub-pdf/ijmer-14.pdf)


<a id="farhat%3A2014oa-year"></a>
[7] S. Farhat, A. Samhat, S. Lahoud, B. Cousin, **Best operator policy in a heterogeneous wireless network**, *e-Technologies and Networks for Development (ICeND), 2014 Third International Conference on*, pp. 53-57, April 2014. [doi](https://doi.org/10.1109/ICeND.2014.6991192) [pdf](http://samer.lahoud.fr/pub-pdf/icend-14.pdf)


<a id="frikha%3A2014kr-year"></a>
[8] A. Frikha, B. Cousin, S. Lahoud, **Applying p-cycle protection for a reliable IPTV service in IP-over-DWDM networks**, *Journal of Internet Services and Applications*, vol. 5, no. 1, 2014. [doi](https://doi.org/10.1186/1869-0238-5-3) [pdf](http://samer.lahoud.fr/pub-pdf/jisa-14.pdf)


<a id="yassin%3A2014ct-year"></a>
[9] M. Yassin, S. Lahoud, M. Ibrahim, K. Khawam, **A Downlink Power Control Heuristic Algorithm for LTE Networks**, *21st International Conference on Telecommunications (ICT 2014)*, Lisbon, Portugal, May 2014. [pdf](http://samer.lahoud.fr/pub-pdf/ict-14.pdf)



## 2013


<a id="el-helou%3A2013sh-year"></a>
[1] M. El Helou, S. Lahoud, M. Ibrahim, K. Khawam, **Satisfaction-based Radio Access Technology Selection in Heterogeneous Wireless Networks**, *Wireless Days (WD), 2013 IFIP*, pp. 1-4, 2013. [doi](https://doi.org/10.1109/WD.2013.6686461) [pdf](http://samer.lahoud.fr/pub-pdf/wd-13.pdf)


<a id="el-helou%3A2013xi-year"></a>
[2] M. El Helou, M. Ibrahim, S. Lahoud, K. Khawam, **Radio Access Selection Approaches in Heterogeneous Wireless Networks**, *2013 IEEE 9th International Conference on Wireless and Mobile Computing, Networking and Communications (WiMob) (WiMob'2013)*, Lyon, France, October 2013. [pdf](http://samer.lahoud.fr/pub-pdf/wimob-13.pdf)


<a id="moety%3A2013jh-year"></a>
[3] F. Moety, S. Lahoud, B. Cousin, K. Khawam, **Power-Delay Tradeoffs in Green Wireless Access Networks**, *VTC Fall 2013*, Las Vegas, USA, 2013. [pdf](http://samer.lahoud.fr/pub-pdf/vtc-13.pdf)


<a id="moety%3A2013ri-year"></a>
[4] F. Moety, S. Lahoud, K. Khawam, B. Cousin, **Joint Power-Delay Minimization in Green Wireless Access Networks**, *2013 IEEE 24th International Symposium on Personal, Indoor and Mobile Radio Communications: Mobile and Wireless Networks (PIMRC'13 - Mobile and Wireless Networks)*, London, United Kingdom, September 2013. [pdf](http://samer.lahoud.fr/pub-pdf/pimrc-13a.pdf)


<a id="khawam%3A2013wm-year"></a>
[5] K. Khawam, J. Cohen, S. Lahoud, P. Muhlethaler, S. Tohme, **AP association in a IEEE 802.11 WLAN**, *Personal Indoor and Mobile Radio Communications (PIMRC), 2013 IEEE 24th International Symposium on*, pp. 2142-2147, Sept 2013. [pdf](http://samer.lahoud.fr/pub-pdf/pimrc-13b.pdf)


<a id="frikha%3A2013lp-year"></a>
[6] A. Frikha, S. Lahoud, B. Cousin, **A Hybrid End-to-End QoS Path Computation Algorithm for PCE-Based Multi-Domain Networks**, *Journal of Network and Systems Management*, pp. 1-27, 2013. [doi](https://doi.org/10.1007/s10922-013-9273-5) [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/jnsm-13.pdf)


<a id="el-helou%3A2013pz-year"></a>
[7] M. El Helou, S. Lahoud, M. Ibrahim, K. Khawam, **A Hybrid Approach for Radio Access Technology Selection in Heterogeneous Wireless Networks**, *European Wireless 2013 (EW2013)*, Guildford, United Kingdom, April 2013. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/ew-13.pdf)


<a id="yassin%3A2013mq-year"></a>
[8] M. Yassin, S. Lahoud, M. Ibrahim, **A Hybrid Approach for RAT Selection in Wireless Heterogeneous Networks**, *The 3rd International Conference on Communications and Information Technology (ICCIT-2013): Wireless Communications and Signal Processing (ICCIT-2013 WCSP)*, Beirut, Lebanon, June 2013. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/iccit-13.pdf)



## 2012


<a id="molnar%3A2012iw-year"></a>
[1] M. Molnar, A. Bellabas, S. Lahoud, **The cost optimal solution of the multi-constrained multicast routing problem**, *Computer Networks*, vol. 56, no. 13, pp. 3136 - 3149, 2012. [doi](https://doi.org/10.1016/j.comnet.2012.04.020)


<a id="frikha%3A2012xh-year"></a>
[2] A. Frikha, S. Lahoud, B. Cousin, M. Molnar, **Reliable Multicast Sessions Provisioning in Sparse Light-Splitting DWDM Networks using P-Cycles**, *2012 Annual IEEE Communications Quality and Reliability International Workshop (CQR2012)*, San Diego CA, USA, May 2012. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/cqr-12.pdf)


<a id="belghith%3A2012oy-year"></a>
[3] A. Belghith, S.B. Said, B. Cousin, S. Lahoud, **QoS Fault Detection and Localization Mechanisms (FDLM) in Multi-domain Networks Adapted to Export Methods**, *4th International Conference on Advanced Communication Technology 2012 (ICACT 2012)*, PyeongChang, Korea, 2012. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/icact-12.pdf)


<a id="belghith%3A2012pt-year"></a>
[4] A. Belghith, S.B. Said, B. Cousin, S. Lahoud, **Proactive and Reactive Collaboration Schemes for Multi-domain Networks Monitoring**, *Engineering-IT applications 2012 (EITA 2012)*, Hong Kong, P.R. China, 2012. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/comcomap-12.pdf)


<a id="bellabas%3A2012ez-year"></a>
[5] A. Bellabas, S. Lahoud, M. Molnar, **Performance Evaluation of Efficient Solutions for the QoS Unicast Routing**, *Journal of Networks*, vol. 7, no. 1, pp. 73-80, January 2012. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/jnet-11.pdf)


<a id="salhi%3A2012bu-year"></a>
[6] E. Salhi, S. Lahoud, B. Cousin, **Localization of Single Link-Level Network Anomalies**, *21st International Conference on Computer Communications and Networks (ICCCN 2012)*, Munich, Germany, July 2012. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/icccn-12.pdf)


<a id="belghith%3A2012zh-year"></a>
[7] A. Belghith, S.B.H. Said, B. Cousin, S. Lahoud, **Export Methods in Fault Detection and Localization Mechanisms**, *IJCSI International Journal of Computer Science Issues*, vol. 9, no. 2, July 2012. [pdf](http://www.ijcsi.org/papers/IJCSI-9-4-2-463-471.pdf)


<a id="moety%3A2012wa-year"></a>
[8] F. Moety, M. Ibrahim, S. Lahoud, K. Khawam, **Distributed Heuristic Algorithms for RAT Selection in Wireless Heterogeneous Networks**, *2012 IEEE Wireless Communications and Networking Conference: Mobile and Wireless Networks (IEEE WCNC 2012 Track 3 Mobile & Wireless)*, Paris, France, April 2012. [pdf](http://dl.dropbox.com/u/45967765/Publications/wcnc-12.pdf)


<a id="belghith%3A2012ta-year"></a>
[9] A. Belghith, S.B.H. Said, B. Cousin, S. Lahoud, **Collaboration Schemes Evaluation in Multi-domain Networks**, *IJCSI International Journal of Computer Science Issues*, vol. 9, no. 2, July 2012. [pdf](http://www.ijcsi.org/papers/IJCSI-9-4-2-472-480.pdf)


<a id="frikha%3A2012dl-year"></a>
[10] A. Frikha, S. Lahoud, B. Cousin, **Candidate-Cycle-based Heuristic Algorithm for Node-and-Link Protection of Dynamic Multicast Traffic in Optical DWDM Networks**, *The International Conference on Information Networking (ICOIN 2012)*, Bali, Indonesia, February 2012. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/icoin-12.pdf)



## 2011


<a id="jawhar%3A2011nq-year"></a>
[1] S. Jawhar, B. Cousin, S. Lahoud, **Required Density of Multicast Capable Optical Cross-Connects to Assure Efficient Multicasting**, *First International Conference on Networking and Future Internet (ICNFI 2011)*, Paris, France, 2011. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/icnfi-11.pdf)


<a id="belghith%3A2011ix-year"></a>
[2] A. Belghith, B. Cousin, S. Lahoud, S.B. Said, **Proposal for the Configuration of multi-domain Network Monitoring Architecture**, *The International Conference on Information Networking (ICOIN 2011)*, Kuala Lumpur, Malaysia, pp. 7 - 12, January 2011. [doi](https://doi.org/10.1109/ICOIN.2011.5723105) [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/icoin-11.pdf)


<a id="jawhar%3A2011gd-year"></a>
[3] S. Jawhar, B. Cousin, S. Lahoud, **Placement of Light Splitters in Optical Networks**, *Deuxième colloque sur les réseaux large bande et Internet rapide*, Beirut, Lebanon, March 2011. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/relabira-11.pdf)


<a id="frikha%3A2011qz-year"></a>
[4] A. Frikha, S. Lahoud, **Performance Evaluation of Pre-computation Algorithms for Inter-Domain QoS Routing**, *The 18th International Conference on Telecommunications, ICT 2011*, Ayia Napa, Cyprus, 5 2011. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/ict-11.pdf)


<a id="khawam%3A2011gs-year"></a>
[5] K. Khawam, M. Ibrahim, J. Cohen, S. Lahoud, S. Tohme, **Individual vs. Global Radio Resource Management in a Hybrid Broadband Network**, *ICC 2011 Wireless Networking Symposium, ICC'11 WNS*, kyoto, Japan, 6 2011. [pdf](http://dl.dropbox.com/u/45967765/Publications/icc-11a.pdf)


<a id="frikha%3A2011lc-year"></a>
[6] A. Frikha, S. Lahoud, B. Cousin, **Hybrid Inter-Domain QoS Routing with Crankback Mechanisms**, In *Smart Spaces and Next Generation Wired/Wireless Networking*, edited by S. Balandin, Y. Koucheryavy, H. Hu, Springer Berlin / Heidelberg, pp. 450-462, 2011. [doi](https://doi.org/10.1007/978-3-642-22875-9_41) [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/new2wan-11.pdf)


<a id="salhi%3A2011ov-year"></a>
[7] E. Salhi, S. Lahoud, B. Cousin, **Heuristics for Joint Optimization of Monitor Location and Network Anomaly Detection**, *ICC 2011 Communications QoS, Reliability and Modeling Symposium (ICC'11 CQRM)*, Kyoto, Japan, 6 2011. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/icc-11b.pdf)


<a id="salhi%3A2011wq-year"></a>
[8] E. Salhi, S. Lahoud, B. Cousin, **Global Vs. Per-Domain Monitoring of Multi-Domain Networks**, *36th Annual IEEE Conference on Local Computer Networks (LCN 2011)*, Bonn, Germany, pp. 391 - 398, 2011. [doi](https://doi.org/10.1109/LCN.2011.6115321) [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/lcn-11b.pdf)


<a id="frikha%3A2011km-year"></a>
[9] A. Frikha, B. Cousin, S. Lahoud, **Extending node protection concept of p-cycles for an efficient resource utilization in multicast traffic**, *Local Computer Networks (LCN), 2011 IEEE 36th Conference on*, Bonn, Germany, pp. 175 -178, oct. 2011. [doi](https://doi.org/10.1109/LCN.2011.6115180) [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/lcn-11a.pdf)


<a id="jawhar%3A2011rw-year"></a>
[10] S. Jawhar, B. Cousin, S. Lahoud, **Effect of Splitting Factor on the Generated Multicast Trees in Optical Networks**, *International Conference on Network Communication and Computer (ICNCC 2011)*, New Delhi, India, pp. 127 - 130, 2011. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/icncc-11.pdf)


<a id="djarallah%3A2011dd-year"></a>
[11] N. Djarallah, N.L. Sauze, H. Pouyllau, S. Lahoud, B. Cousin, **Distributed E2E QoS-Based Path Computation Algorithm Over Multiple Inter-Domain Routes**, *Sixth International Conference on P2P, Parallel, Grid, Cloud and Internet Computing (3PGCIC 2011)*, BARCELONA, Spain, pp. 169 - 176, 2011. [doi](https://doi.org/10.1109/3PGCIC.2011.34) [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/3pgcic-11.pdf)


<a id="drid%3A2011zp-year"></a>
[12] H. Drid, L. Gonczy, S. Lahoud, G. Bergmann, M. Molnar, **Dependable Routing Protocol Considering the k-Coverage Problem for Wireless Sensor Networks**, *ICNS 2011: The Seventh International Conference on Networking and Services*, Venice, Italy, 2011. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/icns-11.pdf)


<a id="bellabas%3A2011rp-year"></a>
[13] A. Bellabas, G. Texier, S. Lahoud, A. Najah, **Convergent IPTV Services over IP Multimedia Subsystem**, *The 14th International Symposium on Wireless Personal Multimedia Communications (WPMC'11)*, Brest, France, 2011. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/wpmc-11.pdf)



## 2010


<a id="drid%3A2010vo-year"></a>
[1] H. Drid, S. Lahoud, B. Cousin, M. Molnar, **Survivability in multi-domain optical networks using p-cycles**, *Photonic Network Communications*, vol. 19, pp. 81-89, 2010. [doi](https://doi.org/10.1007/s11107-009-0213-y) [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/photonic-09.pdf)


<a id="lahoud%3A2010kc-year"></a>
[2] S. Lahoud, **Réseaux locaux**, In *Technologies logicielles Architectures des systèmes*, edited by No Author, Techniques de l'ingénieur, 2010. [pdf](http://www.techniques-ingenieur.fr/base-documentaire/electronique-et-technologies-de-l-information-et-de-la-communication-th9/technologies-logicielles-architectures-des-systemes-ti402/reseaux-locaux-te7000/)


<a id="bertrand%3A2010vz-year"></a>
[3] G. Bertrand, S. Lahoud, G. Texier, M. Molnar, **QoS Routing and Management in Backbone Networks**, In *Intelligent Quality of Service Technologies and Network Management: Models for Enhancing Communication*, edited by P. Bhattarakosol, IGI Global, Hershey, Pennsylvania, USA, pp. 138-159, 2010. [doi](https://doi.org/10.4018/978-1-61520-791-6.ch008) [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/igi-10.pdf)


<a id="frikha%3A2010yi-year"></a>
[4] A. Frikha, S. Lahoud, **Pre-computation based heuristic for inter-domain QoS routing**, *Fourth IEEE International Conference on Advanced Networks and Telecommunication Systems (ANTS) (IEEE ANTS 2010)*, Mumbai, India, pp. 61 -63, dec. 2010. [doi](https://doi.org/10.1109/ANTS.2010.5983529) [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/ants-10.pdf)


<a id="salhi%3A2010km-year"></a>
[5] E. Salhi, S. Lahoud, B. Cousin, **Joint Optimization of Monitor Location and Network Anomaly Detection**, *35th Annual IEEE Conference on Local Computer Networks, LCN 2010*, Denver, Colorado, USA, pp. 204-207, October 2010. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/lcn-10.pdf)


<a id="bertrand%3A2010kq-year"></a>
[6] G. Bertrand, S. Lahoud, G. Texier, M. Molnar, **Inter-Domain Path Computation with Multiple QoS Constraints**, In *Recent Advances in Providing QoS and Reliability in the Future Internet Backbone*, edited by N. Wang, G. Pavlou, M. Boucadair, Nova Science Publisher, 2010. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/nova-10.pdf)


<a id="bellabas%3A2010yj-year"></a>
[7] A. Bellabas, S. Lahoud, M. Molnar, **Fast Heuristics for the QoS Multicast Routing Problem**, *IEEE Globecom 2010 - Communications QoS, Reliability and Modelling Symposium (GC10 - CQRM)*, Miami, Florida, USA, December 2010. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/globecom-10.pdf)


<a id="jawhar%3A2010hc-year"></a>
[8] S. Jawhar, B. Cousin, S. Lahoud, **Efficient Placement of Light Splitters for Heterogeneous Multicast Traffic in Optical Networks**, *High Capacity Optical Networks and Enabling Technologies (HONET)*, Cairo, Egypt, pp. 204 - 209, 2010. [doi](https://doi.org/10.1109/HONET.2010.5715774) [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/honet-10.pdf)


<a id="drid%3A2010tp-year"></a>
[9] H. Drid, B. Cousin, M. Molnar, S. Lahoud, **A Survey of Survivability in Multi-domain Optical Networks**, *Computer Communications*, vol. 33, no. 8, pp. 1005 - 1012, 2010. [doi](https://doi.org/10.1016/j.comcom.2010.02.003) [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/comcom-10.pdf)



## 2009


<a id="bellabas%3A2009mk-year"></a>
[1] A. Bellabas, G. Bertrand, S. Lahoud, G. Texier, M. Molnar, **Quality of Service Routing in Next Generation Networks**, *Colloque Francophone sur l'Ingenierie des Protocoles*, Strasbourg, France, 2009. [pdf](http://hal.inria.fr/inria-00538269/en/)


<a id="drid%3A2009tn-year"></a>
[2] H. Drid, B. Cousin, S. Lahoud, M. Molnar, **Protection par p-cycles dans les réseaux WDM**, *Technique et science informatiques*, vol. 28, no. 4, pp. 20, 2009. [doi](https://doi.org/10.3166/tsi.28.459-478) [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/tsi-09.pdf)


<a id="douville%3A2009lg-year"></a>
[3] R. Douville, S. Lahoud, **Path Computing Element Providing Customized Objective Function**, European Patent Application EP2066086, 2009. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/patent-objective-function.pdf)


<a id="lahoud%3A2009li-year"></a>
[4] S. Lahoud, R. Douville, **Method and Apparatus for Computing a Path in a Network**, European Patent Application EP2063585, 2009. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/patent-computing-path.pdf)


<a id="bellabas%3A2009yg-year"></a>
[5] A. Bellabas, M. Molnar, S. Lahoud, **Heuristiques pour le routage multicritère**, *MAnifestation des JEunes Chercheurs en Sciences et Technologies de l'Information et de la Communication*, Avigon, France, 2009. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/majecstic-09.pdf)


<a id="bellabas%3A2009tg-year"></a>
[6] A. Bellabas, M. Molnar, S. Lahoud, **Heuristics for the Multicriteria Routing Problem**, *Mosharaka International Conference on Communications Computers and Applications*, Amman, Jordan, 2009. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/miccca-09.pdf)


<a id="bertrand%3A2009qm-year"></a>
[7] G. Bertrand, S. Lahoud, G. Texier, M. Molnar, **Computation of Multi-Constrained Paths in Multi-Domain MPLS-TE Networks**, *Next Generation Internet Networks, NGI '09*, Aveiro, Portugal, pp. 1 -8, July 2009. [doi](https://doi.org/10.1109/NGI.2009.5175757) [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/ngi-09.pdf)


<a id="drid%3A2009fd-year"></a>
[8] H. Drid, S. Lahoud, B. Cousin, M. Molnar, **A Topology Aggregation Model for Survivability in Multi-Domain Optical Networks Using p-Cycles**, *Sixth IFIP Inter ional Conference on Network and Parallel Computing, 2009, NPC '09*, Gold Coast, Australia, pp. 211 -218, October 2009. [doi](https://doi.org/10.1109/NPC.2009.21) [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/npc-09.pdf)


<a id="bertrand%3A2009dt-year"></a>
[9] G. Bertrand, S. Lahoud, G. Texier, M. Molnar, **A Distributed Exact Solution to Compute Inter-domain Multi-constrained Paths**, In *The Internet of the Future*, edited by M. Oliver, S. Sallent, Springer Berlin, Heidelberg, Barcelona, Spain, pp. 21-30, 2009. [doi](https://doi.org/10.1007/978-3-642-03700-9_3) [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/eunice-09.pdf)



## 2008


<a id="drid%3A2008vp-year"></a>
[1] H. Drid, B. Cousin, S. Lahoud, M. Molnar, **Multi-criteria p-cycle network design**, *33rd IEEE Conference on Local Computer Networks, LCN 2008*, Montréal, Canada, pp. 361 -366, October 2008. [doi](https://doi.org/10.1109/LCN.2008.4664191) [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/lcn-08.pdf)



## 2006


<a id="lahoud%3A2006rp-year"></a>
[1] S. Lahoud, G. Texier, L. Toutain, **Flow Allocation with Path Protection in Next Generation Internet Networks**, *IEEE International Conference on Communications, ICC '06*, Istanbul, Turkey, pp. 860 -865, June 2006. [doi](https://doi.org/10.1109/ICC.2006.254815) [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/icc-06.pdf)


<a id="lahoud%3A2006zl-year"></a>
[2] S. Lahoud, G. Texier, L. Toutain, **Approximation algorithm for minimum cost flow allocation with varied survivability**, *2nd Conference on Next Generation Internet Design and Engineering, NGI '06*, Valencia, Spain, pp. 8 pp. -299, 2006. [doi](https://doi.org/10.1109/NGI.2006.1678254) [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/ngi-06.pdf)



## 2005


<a id="lahoud%3A2005ws-year"></a>
[1] S. Lahoud, G. Texier, L. Toutain, **Off-line Flow Allocation for Traffic Engineering in MPLS Networks**, *Third International Working Conference on Performance Modelling and Evaluation of Heterogeneous Networks, HET-NETs*, West Yorkshire, U.K, 2005. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/hetnets-05.pdf)


<a id="lahoud%3A2005sh-year"></a>
[2] S. Lahoud, **Fully polynomial approximation for survivable flow allocation with max-min fairness**, *CoNEXT '05: Proceedings of the 2005 ACM conference on Emerging network experiment and technology*, Toulouse, France, pp. 262–263, 2005. [doi](https://doi.org/10.1145/1095921.1095971) [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/conext-05.pdf)


<a id="lahoud%3A2005kv-year"></a>
[3] S. Lahoud, G. Texier, L. Toutain, **FATE: a polynomial time framework for flow allocation in MPLS-TE networks**, *The 14th IEEE Workshop on Local and Metropolitan Area Networks, LANMAN 2005*, Crete, Greece, pp. 6 pp. -6, September 2005. [doi](https://doi.org/10.1109/LANMAN.2005.1541532) [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/lanman-05.pdf)



## 2004


<a id="lahoud%3A2004dg-year"></a>
[1] S. Lahoud, G. Texier, L. Toutain, **Serveur de Topologie OSPF**, *6èmes Journées Doctorales Informatique et Réseau, JDIR*, Lannion, France, 2004. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/jdir-04.pdf)


<a id="lahoud%3A2004ht-year"></a>
[2] S. Lahoud, G. Texier, L. Toutain, **Classification and Evaluation of Constraint-Based Routing Algorithms for MPLS Traffic Engineering**, *6èmes rencontres francophones sur les aspects algorithmiques des télécommunications, Algotel*, Batz-sur-mer, France, 2004. [pdf](http://dl.dropboxusercontent.com/u/45967765/Publications/algotel-04.pdf)



</div>

<script>
document.addEventListener("DOMContentLoaded", function () {
  const buttons = document.querySelectorAll(".pub-view-button");
  const panels = document.querySelectorAll(".pub-view");

  buttons.forEach((button) => {
    button.addEventListener("click", function () {
      const target = button.getAttribute("data-view-target");

      buttons.forEach((item) => {
        item.classList.toggle("is-active", item === button);
      });

      panels.forEach((panel) => {
        panel.hidden = panel.getAttribute("data-view-panel") !== target;
      });
    });
  });
});
</script>